import type { ToolDefinition } from "./types";
import { EMAIL_WRITER_FAQ_ITEMS } from "./tools/email-writer/constants";
import { EMI_FAQ_ITEMS, EMI_FORMULA, EMI_EXAMPLE } from "./tools/emi-calculator/constants";
import { SIP_FAQ_ITEMS, SIP_FORMULA, SIP_EXAMPLE } from "./tools/sip-calculator/constants";
import { LOAN_FAQ_ITEMS, LOAN_FORMULA, LOAN_EXAMPLE } from "./tools/loan-calculator/constants";
import { FD_FAQ_ITEMS, FD_FORMULA, FD_EXAMPLE } from "./tools/fd-calculator/constants";
import { RD_FAQ_ITEMS, RD_FORMULA, RD_EXAMPLE } from "./tools/rd-calculator/constants";
import { SWP_FAQ_ITEMS, SWP_FORMULA, SWP_EXAMPLE } from "./tools/swp-calculator/constants";
import {
  COMPOUND_INTEREST_FAQ_ITEMS,
  COMPOUND_INTEREST_FORMULA,
  COMPOUND_INTEREST_EXAMPLE,
} from "./tools/compound-interest-calculator/constants";
import {
  RETIREMENT_FAQ_ITEMS,
  RETIREMENT_FORMULA,
  RETIREMENT_EXAMPLE,
} from "./tools/retirement-calculator/constants";
import { CAGR_FAQ_ITEMS, CAGR_FORMULA, CAGR_EXAMPLE } from "./tools/cagr-calculator/constants";
import { YOUTUBE_GENERATOR_CONTENT } from "./tools/youtube-generator/tool-content";
import { TIMESTAMP_FAQ_ITEMS, TIMESTAMP_EXAMPLE } from "./tools/youtube-timestamp-generator/constants";
import { THUMBNAIL_FAQ_ITEMS, THUMBNAIL_EXAMPLE } from "./tools/youtube-thumbnail-downloader/constants";
import { INSTAGRAM_GENERATOR_CONTENT } from "./tools/instagram-generator/tool-content";
import {
  ENGAGEMENT_FAQ_ITEMS,
  ENGAGEMENT_EXAMPLE,
} from "./tools/instagram-engagement-calculator/constants";
import {
  CHARACTER_COUNTER_FAQ_ITEMS,
  CHARACTER_COUNTER_EXAMPLE,
} from "./tools/instagram-character-counter/constants";
import { LINKEDIN_GENERATOR_CONTENT } from "./tools/linkedin-generator/tool-content";
import { OPTIMIZER_FAQ_ITEMS, OPTIMIZER_EXAMPLE } from "./tools/linkedin-profile-optimizer/constants";
import {
  HEADLINE_ANALYZER_FAQ_ITEMS,
  HEADLINE_ANALYZER_EXAMPLE,
} from "./tools/linkedin-headline-analyzer/constants";
import {
  PROFILE_SEO_FAQ_ITEMS,
  PROFILE_SEO_EXAMPLE,
} from "./tools/linkedin-profile-seo-checker/constants";
import { TWITTER_GENERATOR_CONTENT } from "./tools/twitter-generator/tool-content";
import { FACEBOOK_GENERATOR_CONTENT } from "./tools/facebook-generator/tool-content";
import { SEO_GENERATOR_CONTENT } from "./tools/seo-generator/tool-content";
import { ROBOTS_FAQ_ITEMS, ROBOTS_EXAMPLE } from "./tools/robots-txt-generator/constants";
import { SITEMAP_FAQ_ITEMS, SITEMAP_EXAMPLE } from "./tools/sitemap-generator/constants";
import { CANONICAL_FAQ_ITEMS, CANONICAL_EXAMPLE } from "./tools/canonical-url-generator/constants";
import { OPEN_GRAPH_FAQ_ITEMS, OPEN_GRAPH_EXAMPLE } from "./tools/open-graph-generator/constants";
import { TWITTER_CARD_FAQ_ITEMS, TWITTER_CARD_EXAMPLE } from "./tools/twitter-card-generator/constants";
import { SCHEMA_FAQ_ITEMS, SCHEMA_EXAMPLE } from "./tools/schema-generator/constants";
import { FAQ_SCHEMA_FAQ_ITEMS, FAQ_SCHEMA_EXAMPLE } from "./tools/faq-schema-generator/constants";
import {
  KEYWORD_DENSITY_FAQ_ITEMS,
  KEYWORD_DENSITY_EXAMPLE,
} from "./tools/keyword-density-checker/constants";
import { JSON_FORMATTER_FAQ_ITEMS, JSON_FORMATTER_EXAMPLE } from "./tools/json-formatter/constants";
import { JSON_VALIDATOR_FAQ_ITEMS, JSON_VALIDATOR_EXAMPLE } from "./tools/json-validator/constants";
import { BASE64_ENCODER_FAQ_ITEMS, BASE64_ENCODER_EXAMPLE } from "./tools/base64-encoder/constants";
import { BASE64_DECODER_FAQ_ITEMS, BASE64_DECODER_EXAMPLE } from "./tools/base64-decoder/constants";
import { UUID_FAQ_ITEMS, UUID_EXAMPLE } from "./tools/uuid-generator/constants";
import { PASSWORD_FAQ_ITEMS, PASSWORD_EXAMPLE } from "./tools/password-generator/constants";
import { HASH_FAQ_ITEMS, HASH_EXAMPLE } from "./tools/hash-generator/constants";
import { HTML_MINIFIER_FAQ_ITEMS, HTML_MINIFIER_EXAMPLE } from "./tools/html-minifier/constants";
import { CSS_MINIFIER_FAQ_ITEMS, CSS_MINIFIER_EXAMPLE } from "./tools/css-minifier/constants";
import { JS_MINIFIER_FAQ_ITEMS, JS_MINIFIER_EXAMPLE } from "./tools/javascript-minifier/constants";
import { WRITING_GENERATOR_CONTENT } from "./tools/writing-generator/tool-content";
import { MEETING_SUMMARY_FAQ_ITEMS, MEETING_SUMMARY_EXAMPLE } from "./tools/meeting-notes-summarizer/constants";
import { REGEX_FAQ_ITEMS, REGEX_EXAMPLE } from "./tools/regex-generator/constants";
import { PALETTE_FAQ_ITEMS, PALETTE_EXAMPLE } from "./tools/color-palette-generator/constants";
import { CSV_TO_JSON_FAQ_ITEMS, CSV_TO_JSON_EXAMPLE } from "./tools/csv-to-json/constants";
import { QR_FAQ_ITEMS, QR_EXAMPLE } from "./tools/qr-code-generator/constants";
import { JWT_FAQ_ITEMS, JWT_EXAMPLE } from "./tools/jwt-decoder/constants";
import { URL_CODEC_FAQ_ITEMS, URL_CODEC_EXAMPLE } from "./tools/url-encoder-decoder/constants";
import { SLUG_FAQ_ITEMS, SLUG_EXAMPLE } from "./tools/seo-slug-generator/constants";
import { JSON_TO_CSV_FAQ_ITEMS, JSON_TO_CSV_EXAMPLE } from "./tools/json-to-csv-converter/constants";
import { GST_FAQ_ITEMS, GST_EXAMPLE } from "./tools/gst-calculator/constants";
import {
  COMPRESSOR_FAQ_ITEMS,
  COMPRESSOR_EXAMPLE,
  RESIZER_FAQ_ITEMS,
  RESIZER_EXAMPLE,
  PNG_TO_JPG_FAQ_ITEMS,
  PNG_TO_JPG_EXAMPLE,
  JPG_TO_PNG_FAQ_ITEMS,
  JPG_TO_PNG_EXAMPLE,
  WEBP_FAQ_ITEMS,
  WEBP_EXAMPLE,
} from "./tools/image-studio/constants";

/**
 * The tool catalog. To add tool #101, add one object here and drop its
 * component under `components/tools/<slug>/` (registering its loader in
 * `lib/tool-components.ts`). Nothing else — routing, the homepage grid,
 * category pages, search, breadcrumbs, and related tools — needs to
 * change.
 *
 * Every field here is plain, serializable data (strings, numbers,
 * booleans, arrays, and plain objects) — no component references, no
 * functions — so this array is safe to read from Client Components
 * (search, the tools browser) as well as Server Components.
 */
export const TOOLS: ToolDefinition[] = [
  {
    slug: "email-writer",
    name: "AI Email Writer",
    tagline: "Write the email. We'll find the words.",
    description:
      "Describe what you need to say, choose a tone and a length, and get a ready-to-send subject line and body in seconds.",
    introParagraph:
      "Staring at a blank subject line is its own kind of writer's block, and it's usually the emails that matter most — a follow-up after an interview, a tricky message to a client, a cover letter you've rewritten four times — that stall the longest. The AI Email Writer takes a rough description of what you need to say, a tone (formal, friendly, direct), and a target length, and turns it into a complete subject line and body you can send as-is or use as a strong first draft. It's built for the moment you know what you want to communicate but not how to phrase it: a status update that needs to sound confident without overselling, a decline that needs to stay warm, a pitch that needs one clean paragraph instead of five rambling ones. Freelancers, job seekers, and anyone who sends more email than they'd like all use it the same way — describe the situation, generate, adjust the specifics, send. It won't know details you haven't given it, so the more context in your prompt, the better the draft; treat the output as a strong starting point tailored to your voice, not a template to copy blindly.",
    category: "writing",
    iconName: "Mail",
    keywords: ["email", "writer", "generator", "ai", "professional email", "cover letter"],
    status: "live",
    addedAt: "2026-06-01",
    faq: EMAIL_WRITER_FAQ_ITEMS,
  },
  {
    slug: "resume-builder",
    name: "AI Resume Builder",
    tagline: "A sharper resume in one pass.",
    description:
      "Turn a rough work history into a clean, recruiter-ready resume, tailored to the role you're applying for.",
    introParagraph:
      "A resume rarely fails because the person's experience wasn't good enough — it fails because the experience never got translated into the specific, quantified language that actually gets read. The AI Resume Builder takes a rough description of your background and your target role and turns it into a structured draft: a short professional summary, action-oriented experience bullets, and a relevant skills line, all shaped around what a recruiter or hiring manager for that specific role would actually want to see. It's genuinely useful for two different moments — writing a first resume from scratch when you don't know where to start, and reworking an existing one for a career change, where your past titles don't obviously map to where you're headed next. It works only from what you actually tell it, so the single biggest thing you can do to improve the output is include real numbers: team size, percentage growth, budget managed, anything concrete. Treat the result as a strong structural draft to personalize, not a finished document — the specific project names, exact dates, and small details that make a resume feel authentic still need to come from you.",
    category: "writing",
    iconName: "FileText",
    keywords: ["resume", "cv", "job application", "career"],
    status: "live",
    addedAt: "2026-09-23",
    applicationCategory: "BusinessApplication",
    faq: WRITING_GENERATOR_CONTENT["resume-builder"].faq,
    example: WRITING_GENERATOR_CONTENT["resume-builder"].example,
  },
  {
    slug: "meeting-notes-summarizer",
    name: "Meeting Notes Summarizer",
    tagline: "Raw notes in, clear action items out.",
    description:
      "Paste messy meeting notes or a transcript and get a structured summary with decisions and action items.",
    category: "productivity",
    iconName: "ListChecks",
    keywords: ["meetings", "notes", "summary", "action items", "productivity"],
    status: "live",
    addedAt: "2026-09-24",
    applicationCategory: "BusinessApplication",
    faq: MEETING_SUMMARY_FAQ_ITEMS,
    example: MEETING_SUMMARY_EXAMPLE,
  },
  {
    slug: "regex-generator",
    name: "Regex Generator",
    tagline: "Describe the pattern, get the regex.",
    description:
      "Explain what you're trying to match in plain English and get a tested, explained regular expression.",
    category: "developer",
    iconName: "Braces",
    keywords: ["regex", "regular expression", "developer", "pattern matching"],
    status: "live",
    addedAt: "2026-09-25",
    applicationCategory: "DeveloperApplication",
    faq: REGEX_FAQ_ITEMS,
    example: REGEX_EXAMPLE,
  },
  {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    tagline: "A palette that actually goes together.",
    description:
      "Generate harmonious color palettes from a base color using real HSL color-wheel relationships — complementary, analogous, triadic, or monochromatic.",
    introParagraph:
      "Picking a second and third color that actually work with a starting color is a real skill, and most people either default to safe neutrals or end up with a palette that clashes in ways they can't quite articulate why. The Color Palette Generator solves this with actual color theory rather than guesswork: enter a base color and choose a scheme — complementary, analogous, triadic, or monochromatic — and it calculates five colors using real HSL color-wheel relationships, the same math a trained designer would apply by hand. It's built for anyone making a design decision without a design background: a founder picking brand colors, a developer choosing a UI accent palette, a student putting together a presentation that needs to look intentional rather than default. Complementary schemes give the highest contrast and work well for a single accent color against a neutral background; analogous schemes read as calmer and more cohesive, which tends to suit a full palette better than a single bold pairing.",
    category: "design",
    iconName: "Palette",
    keywords: ["colors", "palette", "design", "branding", "ui"],
    status: "live",
    addedAt: "2026-09-26",
    applicationCategory: "DesignApplication",
    faq: PALETTE_FAQ_ITEMS,
    example: PALETTE_EXAMPLE,
  },
  {
    slug: "seo-meta-generator",
    name: "SEO Meta Tag Generator",
    tagline: "A title and description that work as a pair.",
    description:
      "Generate a matched title tag and meta description together in one pass — a complete, ready-to-use meta tag set for any page.",
    category: "marketing",
    iconName: "Tags",
    keywords: ["seo", "meta tags", "marketing", "meta description"],
    status: "live",
    addedAt: "2026-09-27",
    applicationCategory: "BusinessApplication",
    faq: WRITING_GENERATOR_CONTENT["seo-meta-generator"].faq,
    example: WRITING_GENERATOR_CONTENT["seo-meta-generator"].example,
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON Converter",
    tagline: "Clean tabular data, structured instantly.",
    description:
      "Paste CSV and get well-formed JSON out — correctly handles quoted fields, embedded commas, and escaped quotes, not just a naive comma split.",
    category: "data",
    iconName: "FileJson",
    keywords: ["csv", "json", "convert", "data", "file conversion"],
    status: "live",
    addedAt: "2026-09-28",
    applicationCategory: "DeveloperApplication",
    faq: CSV_TO_JSON_FAQ_ITEMS,
    example: CSV_TO_JSON_EXAMPLE,
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    tagline: "Know your monthly payment before you sign.",
    description:
      "Calculate your monthly loan installment (EMI), total interest, and full amortization schedule from your loan amount, interest rate, and tenure.",
    introParagraph:
      "Loan offers are usually presented as a single monthly number, which makes it hard to see how much of that number is actually interest versus principal, or how a slightly different tenure changes the total cost over the life of the loan. The EMI Calculator takes a loan amount, interest rate, and tenure and breaks the equated monthly installment down clearly, alongside the total interest you'll pay and a full amortization view of how the balance shrinks over time. It's built for anyone comparing loan offers before signing — a home loan, a car loan, a personal loan — where a half-percent rate difference or a two-year tenure change can mean a meaningfully different total cost that a single EMI figure doesn't make obvious. The most useful way to use it isn't checking one loan in isolation; it's running the same amount through two or three rate/tenure combinations side by side, since that comparison is usually where the real decision lives, not in any single number alone.",
    category: "finance",
    iconName: "Calculator",
    keywords: [
      "emi",
      "emi calculator",
      "loan calculator",
      "amortization",
      "monthly installment",
      "interest calculator",
      "mortgage calculator",
    ],
    status: "live",
    addedAt: "2026-07-23",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: EMI_FAQ_ITEMS,
    formula: EMI_FORMULA,
    example: EMI_EXAMPLE,
  },
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    tagline: "See what consistent investing actually adds up to.",
    description:
      "Project your SIP's final corpus, total returns, and CAGR from a monthly investment, return rate, and period — with step-up and inflation options.",
    category: "finance",
    iconName: "TrendingUp",
    keywords: [
      "sip",
      "sip calculator",
      "systematic investment plan",
      "mutual fund calculator",
      "investment calculator",
      "compound interest",
      "wealth calculator",
      "step-up sip",
    ],
    status: "live",
    addedAt: "2026-07-24",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: SIP_FAQ_ITEMS,
    formula: SIP_FORMULA,
    example: SIP_EXAMPLE,
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    tagline: "Find your EMI, or find what you can borrow.",
    description:
      "Calculate your monthly payment for a given loan amount, or flip it around and find the loan amount a target monthly payment can support.",
    category: "finance",
    iconName: "Banknote",
    keywords: ["loan calculator", "borrowing calculator", "affordability calculator", "loan amount", "monthly payment"],
    status: "live",
    addedAt: "2026-07-25",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: LOAN_FAQ_ITEMS,
    formula: LOAN_FORMULA,
    example: LOAN_EXAMPLE,
  },
  {
    slug: "fd-calculator",
    name: "FD Calculator",
    tagline: "See exactly what your fixed deposit will be worth.",
    description:
      "Calculate the maturity value and total interest on a fixed deposit from your deposit amount, interest rate, tenure, and compounding frequency.",
    category: "finance",
    iconName: "Lock",
    keywords: ["fd calculator", "fixed deposit calculator", "maturity value", "deposit calculator", "bank deposit"],
    status: "live",
    addedAt: "2026-07-26",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: FD_FAQ_ITEMS,
    formula: FD_FORMULA,
    example: FD_EXAMPLE,
  },
  {
    slug: "rd-calculator",
    name: "RD Calculator",
    tagline: "Small monthly deposits, projected to maturity.",
    description:
      "Calculate your recurring deposit's maturity value and total interest from a monthly deposit amount, interest rate, and tenure.",
    category: "finance",
    iconName: "RefreshCw",
    keywords: ["rd calculator", "recurring deposit calculator", "maturity value", "monthly deposit"],
    status: "live",
    addedAt: "2026-07-27",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: RD_FAQ_ITEMS,
    formula: RD_FORMULA,
    example: RD_EXAMPLE,
  },
  {
    slug: "swp-calculator",
    name: "SWP Calculator",
    tagline: "Turn a lump sum into a monthly income.",
    description:
      "Project how long a lump-sum investment lasts under a systematic withdrawal plan — see your final balance, total withdrawn, and interest earned.",
    category: "finance",
    iconName: "TrendingDown",
    keywords: ["swp calculator", "systematic withdrawal plan", "withdrawal calculator", "retirement income"],
    status: "live",
    addedAt: "2026-07-28",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: SWP_FAQ_ITEMS,
    formula: SWP_FORMULA,
    example: SWP_EXAMPLE,
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    tagline: "See how your money grows on itself.",
    description:
      "Calculate compound growth on a lump sum from a principal, annual rate, time period, and compounding frequency.",
    category: "finance",
    iconName: "Percent",
    keywords: ["compound interest calculator", "interest calculator", "growth calculator", "compounding"],
    status: "live",
    addedAt: "2026-07-29",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: COMPOUND_INTEREST_FAQ_ITEMS,
    formula: COMPOUND_INTEREST_FORMULA,
    example: COMPOUND_INTEREST_EXAMPLE,
  },
  {
    slug: "retirement-calculator",
    name: "Retirement Calculator",
    tagline: "See what your savings could grow into by retirement.",
    description:
      "Project your retirement corpus from your current age, retirement age, current savings, monthly contribution, and expected return.",
    category: "finance",
    iconName: "PiggyBank",
    keywords: ["retirement calculator", "retirement corpus", "retirement planning", "nest egg calculator"],
    status: "live",
    addedAt: "2026-07-30",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: RETIREMENT_FAQ_ITEMS,
    formula: RETIREMENT_FORMULA,
    example: RETIREMENT_EXAMPLE,
  },
  {
    slug: "cagr-calculator",
    name: "CAGR Calculator",
    tagline: "The one smoothed growth rate behind any two numbers.",
    description:
      "Calculate the Compound Annual Growth Rate between an initial and final value over a given time period.",
    category: "finance",
    iconName: "ArrowUpRight",
    keywords: ["cagr calculator", "compound annual growth rate", "growth rate calculator", "investment returns"],
    status: "live",
    addedAt: "2026-07-31",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: CAGR_FAQ_ITEMS,
    formula: CAGR_FORMULA,
    example: CAGR_EXAMPLE,
  },
  {
    slug: "youtube-tag-generator",
    name: "YouTube Tag Generator",
    tagline: "Tags that actually help people find your video.",
    description:
      "Generate three ready-to-use sets of YouTube tags from your video's topic, mixing broad and long-tail keywords for better discoverability.",
    introParagraph:
      "YouTube's search and recommendation system leans heavily on the tags attached to a video, and getting them right is one of the few purely mechanical levers a creator has over discoverability — yet most people either skip tags entirely or reuse the same generic list on every upload. The YouTube Tag Generator takes your video's topic and produces three distinct tag sets, each mixing broad terms (the ones with real search volume and real competition) with longer, more specific phrases that have a genuine chance of ranking. That mix matters: broad-only tags get lost in a sea of established channels, while long-tail-only tags miss the traffic entirely. This is built for anyone actively growing a channel — new creators trying to get their first videos found, and established ones optimizing a backlog of older uploads that never got proper tags. The best use case is pairing it with the Title and Description Generators for the same video, so the tags, title, and description all reinforce the same keyword rather than working against each other.",
    category: "creator-studio",
    iconName: "Tags",
    keywords: ["youtube tag generator", "youtube tags", "video seo", "youtube keywords"],
    status: "live",
    addedAt: "2026-08-01",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["tag-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["tag-generator"].example,
  },
  {
    slug: "youtube-title-generator",
    name: "YouTube Title Generator",
    tagline: "Titles that earn the click without the clickbait.",
    description:
      "Generate three compelling YouTube video title options from your topic — attention-grabbing, search-friendly, and true to your content.",
    category: "creator-studio",
    iconName: "Type",
    keywords: ["youtube title generator", "video title ideas", "youtube seo", "clickable titles"],
    status: "live",
    addedAt: "2026-08-02",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["title-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["title-generator"].example,
  },
  {
    slug: "youtube-description-generator",
    name: "YouTube Description Generator",
    tagline: "A full description draft, not just a blank box.",
    description:
      "Generate three complete, SEO-friendly YouTube video descriptions from your topic and key points — hook, context, and call to action included.",
    category: "creator-studio",
    iconName: "AlignLeft",
    keywords: ["youtube description generator", "video description", "youtube seo description"],
    status: "live",
    addedAt: "2026-08-03",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["description-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["description-generator"].example,
  },
  {
    slug: "youtube-hashtag-generator",
    name: "YouTube Hashtag Generator",
    tagline: "The right mix of broad and niche hashtags.",
    description:
      "Generate three sets of relevant YouTube hashtags for your video's topic, ready to paste into your description.",
    category: "creator-studio",
    iconName: "Hash",
    keywords: ["youtube hashtag generator", "youtube hashtags", "video hashtags"],
    status: "live",
    addedAt: "2026-08-04",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["hashtag-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["hashtag-generator"].example,
  },
  {
    slug: "youtube-channel-name-generator",
    name: "YouTube Channel Name Generator",
    tagline: "A name worth building a brand around.",
    description:
      "Generate three catchy, memorable YouTube channel name ideas from your niche or theme.",
    category: "creator-studio",
    iconName: "AtSign",
    keywords: ["youtube channel name generator", "channel name ideas", "youtube branding"],
    status: "live",
    addedAt: "2026-08-05",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["channel-name-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["channel-name-generator"].example,
  },
  {
    slug: "youtube-video-idea-generator",
    name: "YouTube Video Idea Generator",
    tagline: "Never stare at a blank content calendar again.",
    description:
      "Generate three specific, ready-to-film YouTube video ideas from your channel's niche or topic area.",
    category: "creator-studio",
    iconName: "Lightbulb",
    keywords: ["youtube video ideas", "content ideas generator", "youtube video topics"],
    status: "live",
    addedAt: "2026-08-06",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["video-idea-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["video-idea-generator"].example,
  },
  {
    slug: "youtube-script-generator",
    name: "YouTube Script Generator",
    tagline: "A hook, a body, and an outro — drafted for you.",
    description:
      "Generate three complete YouTube video script drafts from your topic, each with a hook, organized main content, and outro.",
    category: "creator-studio",
    iconName: "ScrollText",
    keywords: ["youtube script generator", "video script writer", "youtube script template"],
    status: "live",
    addedAt: "2026-08-07",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["script-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["script-generator"].example,
  },
  {
    slug: "youtube-keyword-generator",
    name: "YouTube Keyword Generator",
    tagline: "Search phrases real viewers actually type.",
    description:
      "Generate three sets of SEO keyword phrases for your video or channel topic, for use in titles, descriptions, and scripts.",
    category: "creator-studio",
    iconName: "KeyRound",
    keywords: ["youtube keyword generator", "youtube keyword research", "video seo keywords"],
    status: "live",
    addedAt: "2026-08-08",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["keyword-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["keyword-generator"].example,
  },
  {
    slug: "youtube-timestamp-generator",
    name: "YouTube Timestamp Generator",
    tagline: "Chapter markers, calculated instantly.",
    description:
      "Turn a list of chapter titles and their lengths into ready-to-paste YouTube timestamps, calculated automatically.",
    category: "creator-studio",
    iconName: "Timer",
    keywords: ["youtube timestamp generator", "video chapters", "youtube chapter markers"],
    status: "live",
    addedAt: "2026-08-09",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: TIMESTAMP_FAQ_ITEMS,
    example: TIMESTAMP_EXAMPLE,
  },
  {
    slug: "youtube-thumbnail-downloader",
    name: "YouTube Thumbnail Downloader",
    tagline: "Every resolution, one paste away.",
    description:
      "Paste any YouTube video URL to preview and download its thumbnail in every available resolution.",
    introParagraph:
      "YouTube generates several resolutions of every video's thumbnail automatically, but there's no built-in way to actually download one — useful when you're building a video roundup, writing about a video, or just want the original image at full quality instead of a screenshot of a screenshot. The YouTube Thumbnail Downloader takes any video URL and surfaces every available resolution for its thumbnail, letting you preview and download the exact size you need directly from YouTube's own servers. It's a small, specific tool aimed at content creators researching competitors, writers and bloggers referencing a specific video, and anyone building a video collection or playlist page who needs real thumbnail images rather than placeholder graphics. It also comes in handy for something as ordinary as recovering a thumbnail for a video you made yourself but never saved a local copy of. Because it pulls directly from YouTube's CDN rather than generating or caching anything itself, the image quality is always exactly what YouTube itself is serving — nothing recompressed or degraded along the way.",
    category: "creator-studio",
    iconName: "Youtube",
    keywords: ["youtube thumbnail downloader", "download youtube thumbnail", "youtube thumbnail grabber"],
    status: "live",
    addedAt: "2026-08-10",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: THUMBNAIL_FAQ_ITEMS,
    example: THUMBNAIL_EXAMPLE,
  },
  {
    slug: "instagram-caption-generator",
    name: "Instagram Caption Generator",
    tagline: "Captions that sound like you, not an ad.",
    description:
      "Generate three engaging Instagram caption options from your post's topic — authentic, conversational, and ready to post.",
    category: "creator-studio",
    iconName: "MessageCircle",
    keywords: ["instagram caption generator", "instagram captions", "caption ideas"],
    status: "live",
    addedAt: "2026-08-11",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["caption-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["caption-generator"].example,
  },
  {
    slug: "instagram-hashtag-generator",
    name: "Instagram Hashtag Generator",
    tagline: "The right mix, from broad reach to niche discovery.",
    description:
      "Generate three sets of relevant Instagram hashtags for your post, mixing broad and niche-specific tags for better reach.",
    introParagraph:
      "Instagram's own guidance has shifted over the years, but the underlying mechanic hasn't: hashtags are still one of the few ways a post can reach people who don't already follow you, and using the same 10 tags on every post is a reliable way to plateau. The Instagram Hashtag Generator reads your post's topic and returns three hashtag sets, each deliberately mixed across broad, medium-competition, and niche-specific tags — broad tags get your post seen briefly by a lot of people, niche tags get it seen for longer by the right people, and a good set needs both. It's built for creators, small businesses, and anyone managing an Instagram presence who's tired of guessing which 20-30 tags to paste in. The best results come from treating each post individually rather than keeping one saved hashtag list forever — a travel photo and a product shot shouldn't share the exact same tags — and pairing this with the Caption Generator so the whole post, not just the hashtags, is built around one clear topic.",
    category: "creator-studio",
    iconName: "Hash",
    keywords: ["instagram hashtag generator", "instagram hashtags", "hashtags for instagram"],
    status: "live",
    addedAt: "2026-08-12",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["hashtag-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["hashtag-generator"].example,
  },
  {
    slug: "instagram-bio-generator",
    name: "Instagram Bio Generator",
    tagline: "150 characters, made to count.",
    description:
      "Generate three Instagram bio options from a short description of your account — clear, on-brand, and within the 150-character limit.",
    category: "creator-studio",
    iconName: "UserCircle",
    keywords: ["instagram bio generator", "instagram bio ideas", "bio for instagram"],
    status: "live",
    addedAt: "2026-08-13",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["bio-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["bio-generator"].example,
  },
  {
    slug: "instagram-username-generator",
    name: "Instagram Username Generator",
    tagline: "A handle worth building a brand around.",
    description:
      "Generate three catchy, memorable Instagram username ideas from your name or niche.",
    category: "creator-studio",
    iconName: "AtSign",
    keywords: ["instagram username generator", "instagram handle ideas", "username ideas"],
    status: "live",
    addedAt: "2026-08-14",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["username-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["username-generator"].example,
  },
  {
    slug: "instagram-reel-caption-generator",
    name: "Instagram Reel Caption Generator",
    tagline: "A hook fast enough for a fast format.",
    description:
      "Generate three short, punchy Instagram Reel captions from your video's topic, built for the quick pace of short-form video.",
    category: "creator-studio",
    iconName: "Film",
    keywords: ["instagram reel caption generator", "reel captions", "reels caption ideas"],
    status: "live",
    addedAt: "2026-08-15",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["reel-caption-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["reel-caption-generator"].example,
  },
  {
    slug: "instagram-post-idea-generator",
    name: "Instagram Post Idea Generator",
    tagline: "Never stare at a blank content calendar again.",
    description:
      "Generate three specific, ready-to-shoot Instagram post ideas from your account's niche.",
    category: "creator-studio",
    iconName: "Lightbulb",
    keywords: ["instagram post ideas", "content ideas generator", "instagram content calendar"],
    status: "live",
    addedAt: "2026-08-16",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["post-idea-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["post-idea-generator"].example,
  },
  {
    slug: "instagram-story-caption-generator",
    name: "Instagram Story Caption Generator",
    tagline: "Quick, casual, and gone in 24 hours.",
    description:
      "Generate three short, casual Instagram Story captions from what's happening in the moment.",
    category: "creator-studio",
    iconName: "Aperture",
    keywords: ["instagram story caption generator", "story captions", "instagram stories ideas"],
    status: "live",
    addedAt: "2026-08-17",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["story-caption-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["story-caption-generator"].example,
  },
  {
    slug: "instagram-quote-generator",
    name: "Instagram Quote Generator",
    tagline: "Original, shareable, ready for a quote graphic.",
    description:
      "Generate three original, shareable quotes on any theme, ready to use on an Instagram quote graphic or caption.",
    category: "creator-studio",
    iconName: "Quote",
    keywords: ["instagram quote generator", "quote graphics", "shareable quotes"],
    status: "live",
    addedAt: "2026-08-18",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["quote-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["quote-generator"].example,
  },
  {
    slug: "instagram-engagement-calculator",
    name: "Instagram Engagement Calculator",
    tagline: "Know your rate before you compare it to anyone else's.",
    description:
      "Calculate your Instagram engagement rate from followers, likes, comments, shares, and saves — with a plain-language rating.",
    category: "creator-studio",
    iconName: "TrendingUp",
    keywords: ["instagram engagement calculator", "engagement rate calculator", "instagram engagement rate"],
    status: "live",
    addedAt: "2026-08-19",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: ENGAGEMENT_FAQ_ITEMS,
    example: ENGAGEMENT_EXAMPLE,
  },
  {
    slug: "instagram-character-counter",
    name: "Instagram Character Counter",
    tagline: "Know exactly how much room you have left.",
    description:
      "Count characters, words, hashtags, and mentions for an Instagram caption, bio, or comment — with a heads-up before you hit the limit.",
    category: "creator-studio",
    iconName: "Ruler",
    keywords: ["instagram character counter", "caption character count", "instagram bio character limit"],
    status: "live",
    addedAt: "2026-08-20",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: CHARACTER_COUNTER_FAQ_ITEMS,
    example: CHARACTER_COUNTER_EXAMPLE,
  },
  {
    slug: "linkedin-headline-generator",
    name: "LinkedIn Headline Generator",
    tagline: "More than a job title, in 220 characters.",
    description:
      "Generate three compelling LinkedIn headline options from your role and focus — built to stand out in search and on your profile.",
    introParagraph:
      "The single most common LinkedIn headline is a job title and nothing else, which technically describes the person but does nothing to differentiate them from thousands of others with the same title — and the headline is prime real estate, visible everywhere a profile shows up in search or in someone's feed. The LinkedIn Headline Generator takes a description of your role and what makes your work distinctive and produces three headline options built to go beyond the job title — signaling a specific focus, outcome, or area of expertise instead. It's aimed at anyone actively job searching, open to recruiters finding them, or simply trying to make their profile represent their actual work rather than a generic label. The strongest headlines tend to combine a role with one concrete specialty or result, which is exactly the structure these options are built around — treat the three variations as different angles on the same core story, and pick whichever framing feels most true to how you'd actually describe your work out loud.",
    category: "linkedin-studio",
    iconName: "PenTool",
    keywords: ["linkedin headline generator", "linkedin headline ideas", "professional headline"],
    status: "live",
    addedAt: "2026-08-21",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["headline-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["headline-generator"].example,
  },
  {
    slug: "linkedin-about-generator",
    name: "LinkedIn About Generator",
    tagline: "Your career story, told in your own voice.",
    description:
      "Generate three LinkedIn About section drafts from your background and experience — a natural first-person narrative, not a résumé bullet list.",
    category: "linkedin-studio",
    iconName: "UserCircle",
    keywords: ["linkedin about generator", "linkedin about section", "linkedin bio generator"],
    status: "live",
    addedAt: "2026-08-22",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["about-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["about-generator"].example,
  },
  {
    slug: "linkedin-summary-generator",
    name: "LinkedIn Summary Generator",
    tagline: "The elevator-pitch version of your career.",
    description:
      "Generate three short, punchy professional summaries from your role and strengths — a compact bio for anywhere a full About section doesn't fit.",
    category: "linkedin-studio",
    iconName: "FileText",
    keywords: ["linkedin summary generator", "professional summary generator", "elevator pitch generator"],
    status: "live",
    addedAt: "2026-08-23",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["summary-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["summary-generator"].example,
  },
  {
    slug: "linkedin-post-generator",
    name: "LinkedIn Post Generator",
    tagline: "A hook worth stopping the scroll for.",
    description:
      "Generate three LinkedIn post drafts from your topic — a strong opening hook, genuine insight, and a takeaway that invites comments.",
    category: "linkedin-studio",
    iconName: "Newspaper",
    keywords: ["linkedin post generator", "linkedin post ideas", "linkedin content generator"],
    status: "live",
    addedAt: "2026-08-24",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["post-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["post-generator"].example,
  },
  {
    slug: "linkedin-experience-generator",
    name: "LinkedIn Experience Generator",
    tagline: "Bullet points that lead with impact.",
    description:
      "Generate three sets of LinkedIn work experience bullet points from your role and responsibilities — action-oriented and quantified where possible.",
    category: "linkedin-studio",
    iconName: "History",
    keywords: ["linkedin experience generator", "resume bullet points", "work experience description"],
    status: "live",
    addedAt: "2026-08-25",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["experience-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["experience-generator"].example,
  },
  {
    slug: "linkedin-skills-generator",
    name: "LinkedIn Skills Generator",
    tagline: "The skills recruiters are actually searching for.",
    description:
      "Generate three relevant LinkedIn skills lists from your role or industry, mixing technical and soft skills.",
    category: "linkedin-studio",
    iconName: "Award",
    keywords: ["linkedin skills generator", "linkedin skills list", "resume skills generator"],
    status: "live",
    addedAt: "2026-08-26",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["skills-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["skills-generator"].example,
  },
  {
    slug: "linkedin-recommendation-generator",
    name: "LinkedIn Recommendation Generator",
    tagline: "Specific praise, not generic compliments.",
    description:
      "Generate three LinkedIn recommendation drafts for a colleague from a description of your working relationship — genuine and specific, not generic praise.",
    category: "linkedin-studio",
    iconName: "ThumbsUp",
    keywords: ["linkedin recommendation generator", "linkedin recommendation examples", "colleague recommendation"],
    status: "live",
    addedAt: "2026-08-27",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["recommendation-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["recommendation-generator"].example,
  },
  {
    slug: "linkedin-connection-request-generator",
    name: "LinkedIn Connection Request Generator",
    tagline: "300 characters, made to count.",
    description:
      "Generate three personalized LinkedIn connection request messages from your context — genuine, specific, and within LinkedIn's 300-character limit.",
    category: "linkedin-studio",
    iconName: "UserPlus",
    keywords: ["linkedin connection request", "linkedin message generator", "networking message generator"],
    status: "live",
    addedAt: "2026-08-28",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["connection-request-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["connection-request-generator"].example,
  },
  {
    slug: "linkedin-company-description-generator",
    name: "LinkedIn Company Description Generator",
    tagline: "Say what your company does — clearly.",
    description:
      "Generate three LinkedIn Company Page description drafts from your business details — what you do, who you serve, and what makes you distinct.",
    category: "linkedin-studio",
    iconName: "Building2",
    keywords: ["linkedin company description", "company page about", "business description generator"],
    status: "live",
    addedAt: "2026-08-29",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["company-description-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["company-description-generator"].example,
  },
  {
    slug: "linkedin-job-description-generator",
    name: "LinkedIn Job Description Generator",
    tagline: "A posting candidates will actually read.",
    description:
      "Generate three LinkedIn job posting drafts from your role details — intro, responsibilities, and qualifications, structured the way postings are read.",
    category: "linkedin-studio",
    iconName: "ClipboardList",
    keywords: ["linkedin job description generator", "job posting generator", "job description template"],
    status: "live",
    addedAt: "2026-08-30",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["job-description-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["job-description-generator"].example,
  },
  {
    slug: "linkedin-profile-optimizer",
    name: "LinkedIn Profile Optimizer",
    tagline: "Your existing text, made sharper.",
    description:
      "Paste your current LinkedIn headline or About section to get an improved rewrite plus specific, actionable reasons why it's stronger.",
    category: "linkedin-studio",
    iconName: "Wand2",
    keywords: ["linkedin profile optimizer", "linkedin profile improvement", "linkedin rewrite tool"],
    status: "live",
    addedAt: "2026-08-31",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: OPTIMIZER_FAQ_ITEMS,
    example: OPTIMIZER_EXAMPLE,
  },
  {
    slug: "linkedin-headline-analyzer",
    name: "LinkedIn Headline Analyzer",
    tagline: "Know what's working and what isn't.",
    description:
      "Score your LinkedIn headline against concrete, checkable criteria — length, value-signaling language, quantifiable detail, structure, and formatting.",
    category: "linkedin-studio",
    iconName: "Gauge",
    keywords: ["linkedin headline analyzer", "linkedin headline checker", "linkedin headline score"],
    status: "live",
    addedAt: "2026-09-01",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: HEADLINE_ANALYZER_FAQ_ITEMS,
    example: HEADLINE_ANALYZER_EXAMPLE,
  },
  {
    slug: "linkedin-profile-seo-checker",
    name: "LinkedIn Profile SEO Checker",
    tagline: "See your profile the way search does.",
    description:
      "Check your headline, About section, and skills against your target keywords — with a coverage breakdown and completeness findings.",
    category: "linkedin-studio",
    iconName: "Search",
    keywords: ["linkedin seo checker", "linkedin profile seo", "linkedin keyword checker"],
    status: "live",
    addedAt: "2026-09-02",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: PROFILE_SEO_FAQ_ITEMS,
    example: PROFILE_SEO_EXAMPLE,
  },
  {
    slug: "twitter-tweet-generator",
    name: "Twitter Tweet Generator",
    tagline: "Direct, sharp, and under 280 characters.",
    description:
      "Generate three tweet options from your topic — direct, clear, and written to fit X's character limit.",
    introParagraph:
      "A post with a clear, direct point tends to outperform a meandering one on X, but writing tight, specific text under a 280-character limit is a genuinely different skill from writing a longer piece — every word has to earn its place. The Tweet Generator takes a topic or observation and produces three distinct post options, each written to make one clear point without wasted words, ready to post as-is or adjust to match your own voice. It's built for people actively posting on X — creators building an audience, professionals sharing insight in their field, or anyone who has a good thought and fifteen seconds to turn it into something worth reading. Because tone matters as much as content on this platform, the three generated options are usually genuinely different from each other rather than three phrasings of the same idea — read all three before picking, since the best fit often isn't the first one.",
    category: "creator-studio",
    iconName: "MessageSquare",
    keywords: ["tweet generator", "twitter post generator", "x post generator"],
    status: "live",
    addedAt: "2026-09-03",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["tweet-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["tweet-generator"].example,
  },
  {
    slug: "twitter-viral-tweet-generator",
    name: "Twitter Viral Tweet Generator",
    tagline: "Bolder hooks, sharper takes.",
    description:
      "Generate three tweet options built around bold hooks and sharp takes, structured for higher engagement potential.",
    category: "creator-studio",
    iconName: "Flame",
    keywords: ["viral tweet generator", "viral twitter post", "twitter engagement generator"],
    status: "live",
    addedAt: "2026-09-04",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["viral-tweet-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["viral-tweet-generator"].example,
  },
  {
    slug: "twitter-thread-generator",
    name: "Twitter Thread Generator",
    tagline: "A hook, then a payoff, tweet by tweet.",
    description:
      "Generate three complete X thread outlines from your topic — a strong hook followed by numbered, standalone tweets.",
    category: "creator-studio",
    iconName: "ListOrdered",
    keywords: ["twitter thread generator", "x thread generator", "thread outline generator"],
    status: "live",
    addedAt: "2026-09-05",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["thread-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["thread-generator"].example,
  },
  {
    slug: "twitter-bio-generator",
    name: "Twitter Bio Generator",
    tagline: "160 characters, full of personality.",
    description:
      "Generate three X bio options from your account description — punchy, specific, and within the 160-character limit.",
    category: "creator-studio",
    iconName: "UserCircle",
    keywords: ["twitter bio generator", "x bio generator", "twitter bio ideas"],
    status: "live",
    addedAt: "2026-09-06",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["bio-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["bio-generator"].example,
  },
  {
    slug: "twitter-username-generator",
    name: "Twitter Username Generator",
    tagline: "A handle worth building a following around.",
    description:
      "Generate three catchy, likely-available X handle ideas from your name or niche.",
    category: "creator-studio",
    iconName: "AtSign",
    keywords: ["twitter username generator", "x handle generator", "twitter handle ideas"],
    status: "live",
    addedAt: "2026-09-07",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["username-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["username-generator"].example,
  },
  {
    slug: "twitter-hashtag-generator",
    name: "Twitter Hashtag Generator",
    tagline: "Fewer, better hashtags.",
    description:
      "Generate three small, well-targeted X hashtag sets from your post's topic — quality over quantity.",
    category: "creator-studio",
    iconName: "Hash",
    keywords: ["twitter hashtag generator", "x hashtag generator", "twitter hashtags"],
    status: "live",
    addedAt: "2026-09-08",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["hashtag-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["hashtag-generator"].example,
  },
  {
    slug: "twitter-hook-generator",
    name: "Twitter Hook Generator",
    tagline: "The first line that earns the rest of the read.",
    description:
      "Generate three opening hook lines from your topic — for a standalone tweet or the first line of a thread.",
    category: "creator-studio",
    iconName: "Anchor",
    keywords: ["twitter hook generator", "tweet hook ideas", "thread opener generator"],
    status: "live",
    addedAt: "2026-09-09",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["hook-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["hook-generator"].example,
  },
  {
    slug: "twitter-poll-generator",
    name: "Twitter Poll Generator",
    tagline: "A clear question, options included.",
    description:
      "Generate three X poll options from your topic — a clear question with 2-4 short answer choices, ready to post.",
    category: "creator-studio",
    iconName: "BarChart3",
    keywords: ["twitter poll generator", "x poll generator", "twitter poll ideas"],
    status: "live",
    addedAt: "2026-09-10",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["poll-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["poll-generator"].example,
  },
  {
    slug: "twitter-reply-generator",
    name: "Twitter Reply Generator",
    tagline: "A reply that could stand on its own.",
    description:
      "Generate three X reply options from the context of what you're responding to — adding genuine value, not just agreement.",
    category: "creator-studio",
    iconName: "Reply",
    keywords: ["twitter reply generator", "x reply generator", "tweet reply ideas"],
    status: "live",
    addedAt: "2026-09-11",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["reply-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["reply-generator"].example,
  },
  {
    slug: "twitter-content-calendar",
    name: "Twitter Content Calendar",
    tagline: "A week of ideas, planned in one pass.",
    description:
      "Generate three 7-day X content calendar options from your account's niche — a specific, varied post idea for each day.",
    category: "creator-studio",
    iconName: "Calendar",
    keywords: ["twitter content calendar", "x content calendar", "twitter posting schedule"],
    status: "live",
    addedAt: "2026-09-12",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["content-calendar"].faq,
    example: TWITTER_GENERATOR_CONTENT["content-calendar"].example,
  },
  {
    slug: "facebook-caption-generator",
    name: "Facebook Caption Generator",
    tagline: "Warm, conversational, ready to post.",
    description:
      "Generate three Facebook caption options from your photo or post topic — warm and conversational, Facebook's natural register.",
    category: "creator-studio",
    iconName: "MessageCircle",
    keywords: ["facebook caption generator", "facebook captions", "facebook photo caption"],
    status: "live",
    addedAt: "2026-09-13",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["caption-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["caption-generator"].example,
  },
  {
    slug: "facebook-post-generator",
    name: "Facebook Post Generator",
    tagline: "Room to tell the whole update.",
    description:
      "Generate three Facebook post drafts from your topic — a bit longer and more conversational than other platforms, the way Facebook posts read best.",
    introParagraph:
      "Facebook rewards posts that read like an actual person wrote them for actual friends or followers, not a brand broadcasting an announcement — and that conversational register is harder to write on demand than it sounds, especially for a business account trying to sound approachable without sounding forced. The Facebook Post Generator takes your topic and produces three post drafts in that warmer, more conversational style Facebook posts tend to need, each built around a hook worth reading past the first line and a genuine update or story rather than a flat announcement. It's aimed at small business owners managing their own Page, community managers posting on behalf of a group, and anyone maintaining a presence without a dedicated social media team. Pairing the generated text with an actual photo consistently outperforms text-only posts on this platform specifically, so treat the caption as one half of the post rather than the whole thing.",
    category: "creator-studio",
    iconName: "Newspaper",
    keywords: ["facebook post generator", "facebook post ideas", "facebook content generator"],
    status: "live",
    addedAt: "2026-09-14",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["post-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["post-generator"].example,
  },
  {
    slug: "facebook-bio-generator",
    name: "Facebook Bio Generator",
    tagline: "255 characters that say exactly who you are.",
    description:
      "Generate three Facebook Page or profile bio options from your description — clear and within the 255-character limit.",
    category: "creator-studio",
    iconName: "UserCircle",
    keywords: ["facebook bio generator", "facebook page description", "facebook about section"],
    status: "live",
    addedAt: "2026-09-15",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["bio-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["bio-generator"].example,
  },
  {
    slug: "facebook-ad-copy-generator",
    name: "Facebook Ad Copy Generator",
    tagline: "The primary text that earns the click.",
    description:
      "Generate three Facebook ad primary text options from your offer — persuasive, benefit-led, and structured for the first two lines to earn attention.",
    category: "creator-studio",
    iconName: "Megaphone",
    keywords: ["facebook ad copy generator", "facebook ads copy", "facebook ad text generator"],
    status: "live",
    addedAt: "2026-09-16",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["ad-copy-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["ad-copy-generator"].example,
  },
  {
    slug: "facebook-headline-generator",
    name: "Facebook Headline Generator",
    tagline: "Bold text, 40 characters, straight to the point.",
    description:
      "Generate three Facebook ad headline options from your offer — the short, bold text shown above your ad's primary text.",
    category: "creator-studio",
    iconName: "Type",
    keywords: ["facebook headline generator", "facebook ad headline", "facebook ads headline ideas"],
    status: "live",
    addedAt: "2026-09-17",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["headline-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["headline-generator"].example,
  },
  {
    slug: "facebook-cta-generator",
    name: "Facebook CTA Generator",
    tagline: "A clear next step, not a vague nudge.",
    description:
      "Generate three call-to-action lines from the specific action you want readers to take — a clear, low-friction next step.",
    category: "creator-studio",
    iconName: "MousePointerClick",
    keywords: ["facebook cta generator", "call to action generator", "facebook ad cta"],
    status: "live",
    addedAt: "2026-09-18",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["cta-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["cta-generator"].example,
  },
  {
    slug: "facebook-comment-generator",
    name: "Facebook Comment Generator",
    tagline: "Sounds like a person, not a reply bot.",
    description:
      "Generate three Facebook comment options from the context of what you're responding to — natural, conversational, and genuinely additive.",
    category: "creator-studio",
    iconName: "MessageSquare",
    keywords: ["facebook comment generator", "facebook comment ideas", "facebook reply generator"],
    status: "live",
    addedAt: "2026-09-19",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["comment-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["comment-generator"].example,
  },
  {
    slug: "facebook-event-description-generator",
    name: "Facebook Event Description Generator",
    tagline: "Why someone should actually show up.",
    description:
      "Generate three Facebook Event description options from your event details — clear on what it is, who it's for, and why to attend.",
    category: "creator-studio",
    iconName: "CalendarDays",
    keywords: ["facebook event description", "facebook event generator", "event description ideas"],
    status: "live",
    addedAt: "2026-09-20",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["event-description-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["event-description-generator"].example,
  },
  {
    slug: "facebook-group-description-generator",
    name: "Facebook Group Description Generator",
    tagline: "Set the tone before anyone joins.",
    description:
      "Generate three Facebook Group description options from your group's purpose — clear about who it's for and what to expect.",
    category: "creator-studio",
    iconName: "Users",
    keywords: ["facebook group description", "facebook group generator", "group description ideas"],
    status: "live",
    addedAt: "2026-09-21",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["group-description-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["group-description-generator"].example,
  },
  {
    slug: "facebook-hashtag-generator",
    name: "Facebook Hashtag Generator",
    tagline: "A few well-chosen tags, not a wall of them.",
    description:
      "Generate three small, relevant Facebook hashtag sets from your post's topic.",
    category: "creator-studio",
    iconName: "Hash",
    keywords: ["facebook hashtag generator", "facebook hashtags", "facebook post hashtags"],
    status: "live",
    addedAt: "2026-09-22",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["hashtag-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["hashtag-generator"].example,
  },
  {
    slug: "seo-meta-title-generator",
    name: "Meta Title Generator",
    tagline: "50-60 characters that earn the click.",
    description:
      "Generate three SEO meta title options from your page's topic — keyword-aware and sized to fit search results.",
    introParagraph:
      "A page's title tag does two jobs at once — it's a ranking signal search engines weigh, and it's the literal blue link text a person decides whether to click — and writing one that does both well, inside a roughly 60-character display limit, is genuinely harder than it looks. The Meta Title Generator takes a description of your page's content and produces three distinct title options, each built to include the core topic near the front (where it carries more weight) while still reading as something a person would actually want to click, not a keyword string. It's built for anyone publishing content who's currently leaving titles to be auto-generated from the page's H1 — bloggers, marketers, small business owners maintaining their own site — since a title written on purpose consistently outperforms one nobody thought about. Pairing a generated title with the Meta Description Generator for the same page rounds out the full search-result snippet, rather than optimizing the title in isolation and leaving the description as an afterthought.",
    category: "marketing",
    iconName: "Type",
    keywords: ["meta title generator", "seo title generator", "page title generator"],
    status: "live",
    addedAt: "2026-10-01",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: SEO_GENERATOR_CONTENT["meta-title-generator"].faq,
    example: SEO_GENERATOR_CONTENT["meta-title-generator"].example,
  },
  {
    slug: "seo-meta-description-generator",
    name: "Meta Description Generator",
    tagline: "The line under your title that earns the click.",
    description:
      "Generate three SEO meta description options from your page's topic — sized to fit search results, with a natural call to action.",
    category: "marketing",
    iconName: "AlignLeft",
    keywords: ["meta description generator", "seo description generator", "page description generator"],
    status: "live",
    addedAt: "2026-10-02",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: SEO_GENERATOR_CONTENT["meta-description-generator"].faq,
    example: SEO_GENERATOR_CONTENT["meta-description-generator"].example,
  },
  {
    slug: "seo-robots-txt-generator",
    name: "Robots.txt Generator",
    tagline: "Tell crawlers exactly where to go.",
    description:
      "Build a valid robots.txt file from allow/disallow rules and a sitemap URL — ready to paste at your domain root.",
    category: "marketing",
    iconName: "Bot",
    keywords: ["robots.txt generator", "robots txt", "crawler rules generator"],
    status: "live",
    addedAt: "2026-10-03",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: ROBOTS_FAQ_ITEMS,
    example: ROBOTS_EXAMPLE,
  },
  {
    slug: "seo-sitemap-generator",
    name: "Sitemap Generator",
    tagline: "Every page, mapped for search engines.",
    description:
      "Build a valid XML sitemap from a list of URLs, with change frequency and priority settings applied to each.",
    category: "marketing",
    iconName: "Map",
    keywords: ["sitemap generator", "xml sitemap generator", "sitemap.xml"],
    status: "live",
    addedAt: "2026-10-04",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: SITEMAP_FAQ_ITEMS,
    example: SITEMAP_EXAMPLE,
  },
  {
    slug: "seo-canonical-url-generator",
    name: "Canonical URL Generator",
    tagline: "One clean URL, tracking parameters gone.",
    description:
      "Normalize any URL and generate its canonical tag — strips tracking parameters, enforces https, and cleans up trailing slashes.",
    category: "marketing",
    iconName: "Link",
    keywords: ["canonical url generator", "canonical tag generator", "seo canonical url"],
    status: "live",
    addedAt: "2026-10-05",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: CANONICAL_FAQ_ITEMS,
    example: CANONICAL_EXAMPLE,
  },
  {
    slug: "seo-open-graph-generator",
    name: "Open Graph Generator",
    tagline: "Control how your link looks when shared.",
    description:
      "Build a complete set of Open Graph meta tags from your page's title, description, image, and type.",
    category: "marketing",
    iconName: "Share2",
    keywords: ["open graph generator", "og tags generator", "og meta tags"],
    status: "live",
    addedAt: "2026-10-06",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: OPEN_GRAPH_FAQ_ITEMS,
    example: OPEN_GRAPH_EXAMPLE,
  },
  {
    slug: "seo-twitter-card-generator",
    name: "Twitter Card Generator",
    tagline: "A clean preview, every time it's shared on X.",
    description:
      "Build a complete set of Twitter Card meta tags from your page's title, description, image, and card type.",
    category: "marketing",
    iconName: "LayoutTemplate",
    keywords: ["twitter card generator", "x card generator", "twitter meta tags"],
    status: "live",
    addedAt: "2026-10-07",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: TWITTER_CARD_FAQ_ITEMS,
    example: TWITTER_CARD_EXAMPLE,
  },
  {
    slug: "seo-schema-generator",
    name: "Schema Generator",
    tagline: "Structured data search engines can actually read.",
    description:
      "Build valid schema.org JSON-LD for Article, Product, LocalBusiness, or Person — ready to drop into your page's head.",
    category: "marketing",
    iconName: "Braces",
    keywords: ["schema generator", "json-ld generator", "structured data generator"],
    status: "live",
    addedAt: "2026-10-08",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: SCHEMA_FAQ_ITEMS,
    example: SCHEMA_EXAMPLE,
  },
  {
    slug: "seo-faq-schema-generator",
    name: "FAQ Schema Generator",
    tagline: "Your FAQ, eligible for rich results.",
    description:
      "Build valid FAQPage JSON-LD from a list of question-and-answer pairs — ready to drop into your page's head.",
    category: "marketing",
    iconName: "HelpCircle",
    keywords: ["faq schema generator", "faqpage json-ld", "faq structured data"],
    status: "live",
    addedAt: "2026-10-09",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: FAQ_SCHEMA_FAQ_ITEMS,
    example: FAQ_SCHEMA_EXAMPLE,
  },
  {
    slug: "seo-keyword-density-checker",
    name: "Keyword Density Checker",
    tagline: "See your content the way search engines count it.",
    description:
      "Check word frequency and a target keyword's density in your text — a sanity check against keyword stuffing.",
    introParagraph:
      "Keyword density stopped being a precise ranking lever years ago, but the underlying question it answers is still useful: does this page actually, verifiably contain the language a reader — and a search engine — would expect it to contain, or does it just feel like it does when you're the one who wrote it. The Keyword Density Checker analyzes a block of text against a specific target keyword (or phrase) and reports exactly how often it appears, what percentage of the total word count that represents, and which other words show up most frequently once common filler words are filtered out. It's a sanity check for content writers and SEO practitioners before publishing — catching both keyword stuffing that reads awkwardly and the opposite problem, content that never actually mentions the term it's supposedly targeting. Use it as a diagnostic during editing, not a target to hit exactly; a specific density percentage has never been what search engines actually reward, and writing toward one tends to produce noticeably worse prose than writing for a reader first.",
    category: "marketing",
    iconName: "Percent",
    keywords: ["keyword density checker", "keyword density calculator", "content seo checker"],
    status: "live",
    addedAt: "2026-10-10",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: KEYWORD_DENSITY_FAQ_ITEMS,
    example: KEYWORD_DENSITY_EXAMPLE,
  },
  {
    slug: "dev-json-formatter",
    name: "JSON Formatter",
    tagline: "Compact JSON, made readable.",
    description:
      "Pretty-print JSON with proper indentation, entirely in your browser — with a clear error if it's invalid.",
    introParagraph:
      "Minified or hand-typed JSON — a single unbroken line from an API response, or a config file someone edited in a hurry — is close to unreadable, and squinting at nested braces to find a mismatched bracket is a bad use of anyone's time. The JSON Formatter takes any JSON input and pretty-prints it with consistent 2-space indentation, instantly, entirely in your browser, with the exact parse error shown clearly if the input isn't valid JSON at all. It's a daily tool for developers debugging an API response, reviewing a config file, or cleaning up JSON before pasting it into documentation or a bug report. The formatted result is one click away from being copied or downloaded as a file, so it fits naturally into a workflow that starts with a messy paste and ends with something clean saved or shared. Because nothing is sent to a server, it's also safe to use on JSON containing real data you wouldn't want to paste into a random web tool — API keys, internal config, anything sensitive stays exactly where it was, processed locally and never transmitted.",
    category: "developer",
    iconName: "Braces",
    keywords: ["json formatter", "json pretty print", "json beautifier"],
    status: "live",
    addedAt: "2026-10-11",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: JSON_FORMATTER_FAQ_ITEMS,
    example: JSON_FORMATTER_EXAMPLE,
  },
  {
    slug: "dev-json-validator",
    name: "JSON Validator",
    tagline: "Know exactly where your JSON breaks.",
    description:
      "Check whether your JSON is valid, with a specific error message and location when it isn't.",
    category: "developer",
    iconName: "ShieldCheck",
    keywords: ["json validator", "json checker", "validate json"],
    status: "live",
    addedAt: "2026-10-12",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: JSON_VALIDATOR_FAQ_ITEMS,
    example: JSON_VALIDATOR_EXAMPLE,
  },
  {
    slug: "dev-base64-encoder",
    name: "Base64 Encoder",
    tagline: "Text to Base64, UTF-8 safe.",
    description:
      "Encode text to Base64 entirely in your browser — correctly handles emoji and non-Latin text.",
    category: "developer",
    iconName: "Lock",
    keywords: ["base64 encoder", "base64 encode", "text to base64"],
    status: "live",
    addedAt: "2026-10-13",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: BASE64_ENCODER_FAQ_ITEMS,
    example: BASE64_ENCODER_EXAMPLE,
  },
  {
    slug: "dev-base64-decoder",
    name: "Base64 Decoder",
    tagline: "Base64 back to readable text.",
    description:
      "Decode Base64 back to plain text entirely in your browser — correctly handles emoji and non-Latin text.",
    category: "developer",
    iconName: "Unlock",
    keywords: ["base64 decoder", "base64 decode", "base64 to text"],
    status: "live",
    addedAt: "2026-10-14",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: BASE64_DECODER_FAQ_ITEMS,
    example: BASE64_DECODER_EXAMPLE,
  },
  {
    slug: "dev-uuid-generator",
    name: "UUID Generator",
    tagline: "Unique identifiers, generated instantly.",
    description:
      "Generate one or more RFC 4122 v4 UUIDs using cryptographically secure randomness, entirely in your browser.",
    category: "developer",
    iconName: "Fingerprint",
    keywords: ["uuid generator", "guid generator", "unique id generator"],
    status: "live",
    addedAt: "2026-10-15",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: UUID_FAQ_ITEMS,
    example: UUID_EXAMPLE,
  },
  {
    slug: "dev-password-generator",
    name: "Password Generator",
    tagline: "Cryptographically random, not Math.random().",
    description:
      "Generate a strong password with customizable length and character types, using your browser's secure random number generator.",
    introParagraph:
      "Reusing passwords, or generating them with a mental pattern a person could guess, remains one of the most common ways accounts actually get compromised — and the fix isn't complicated, it's just tedious to do by hand for every new account. The Password Generator produces genuinely random passwords using the browser's cryptographically secure random number generator (not a weaker pseudo-random function), with independent control over length and character types, and a straightforward strength rating so you're not guessing whether a given password is actually strong. It's for anyone setting up a new account, rotating an old password, or standardizing on strong, unique passwords across every service instead of variations on the same one. Visually ambiguous characters (0 versus O, 1 versus l versus I) are excluded by default, which matters if you ever need to type a generated password by hand rather than paste it — a small detail that saves a real, common frustration.",
    category: "developer",
    iconName: "KeyRound",
    keywords: ["password generator", "strong password generator", "random password"],
    status: "live",
    addedAt: "2026-10-16",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: PASSWORD_FAQ_ITEMS,
    example: PASSWORD_EXAMPLE,
  },
  {
    slug: "dev-hash-generator",
    name: "Hash Generator",
    tagline: "SHA-1 through SHA-512, verified correct.",
    description:
      "Hash text using SHA-1, SHA-256, SHA-384, or SHA-512 via your browser's native Web Crypto API.",
    introParagraph:
      "A hash is a one-way fingerprint of some input — the same input always produces the same hash, but the hash can never be reversed back to the original — which makes it useful for exactly the kind of integrity checks and non-reversible comparisons that come up constantly in development work. The Hash Generator computes SHA-1, SHA-256, SHA-384, and SHA-512 hashes using the browser's native, cryptographically verified Web Crypto API — real, standard implementations, not a hand-rolled approximation — entirely client-side. It's a routine tool for developers verifying a file's integrity against a published checksum, generating a deterministic identifier from some input data, or working with any system that expects a specific hash algorithm's output. MD5 is deliberately not offered: it isn't part of the Web Crypto API by design, since it's no longer considered cryptographically secure, and SHA-256 or higher is the right choice for anything where that security property actually matters.",
    category: "developer",
    iconName: "Hash",
    keywords: ["hash generator", "sha256 generator", "sha1 generator"],
    status: "live",
    addedAt: "2026-10-17",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: HASH_FAQ_ITEMS,
    example: HASH_EXAMPLE,
  },
  {
    slug: "dev-html-minifier",
    name: "HTML Minifier",
    tagline: "Comments and blank lines gone, nothing else touched.",
    description:
      "Remove HTML comments and extra blank lines without risking any change to how the page renders.",
    category: "developer",
    iconName: "Code",
    keywords: ["html minifier", "minify html", "html compressor"],
    status: "live",
    addedAt: "2026-10-18",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: HTML_MINIFIER_FAQ_ITEMS,
    example: HTML_MINIFIER_EXAMPLE,
  },
  {
    slug: "dev-css-minifier",
    name: "CSS Minifier",
    tagline: "Comments and blank lines gone, styles untouched.",
    description:
      "Remove CSS comments and extra blank lines without risking any change to your styles.",
    category: "developer",
    iconName: "Palette",
    keywords: ["css minifier", "minify css", "css compressor"],
    status: "live",
    addedAt: "2026-10-19",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: CSS_MINIFIER_FAQ_ITEMS,
    example: CSS_MINIFIER_EXAMPLE,
  },
  {
    slug: "dev-javascript-minifier",
    name: "JavaScript Minifier",
    tagline: "Safe by design — never breaks your code.",
    description:
      "Remove JavaScript comments and extra blank lines, using a string/regex-aware parser that never joins lines or risks breaking ASI-dependent code.",
    category: "developer",
    iconName: "FileCode",
    keywords: ["javascript minifier", "minify javascript", "js minifier"],
    status: "live",
    addedAt: "2026-10-20",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: JS_MINIFIER_FAQ_ITEMS,
    example: JS_MINIFIER_EXAMPLE,
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    tagline: "Any text or URL, instantly scannable.",
    description:
      "Generate a scannable QR code from any text or URL, ready to download or embed.",
    introParagraph:
      "A QR code is one of the few pieces of offline material that can point directly at something online — a menu, a form, a payment link, a WiFi network — and generating one correctly, at a size that actually scans reliably once printed, is worth getting right the first time rather than troubleshooting a code nobody's phone can read. The QR Code Generator turns any URL or text into a scannable code at your choice of size, generated through an established public QR service rather than an unverified in-browser implementation, so what you download is a genuinely reliable, real QR code. It's useful anywhere physical and digital need to connect — a restaurant menu, a business card, a poster linking to an event page, a WiFi network shared without typing a long password. For anything printed and displayed at a distance, size matters more than people expect: a code that scans instantly on a phone six inches away can fail entirely from across a room, so err toward the larger size options for anything on a poster or sign.",
    category: "image-studio",
    iconName: "QrCode",
    keywords: ["qr code generator", "qr code maker", "generate qr code"],
    status: "live",
    addedAt: "2026-10-21",
    applicationCategory: "UtilitiesApplication",
    relatedToolsLimit: 6,
    faq: QR_FAQ_ITEMS,
    example: QR_EXAMPLE,
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    tagline: "Smaller files, right in your browser.",
    description:
      "Compress an image to reduce its file size, with an adjustable quality slider — processed entirely in your browser, nothing uploaded.",
    introParagraph:
      "A photo straight off a modern phone camera is often needlessly large for anything it's actually going to be used for — a web page, an email attachment, a form upload with a size cap — and that extra weight translates directly into slower page loads and, on some platforms, outright upload failures. The Image Compressor re-encodes your image at an adjustable quality level, right in your browser, showing you exactly how much smaller the result is before you download it. It's built for web developers trying to protect their site's load time, anyone attaching images to an email with a size limit, and sellers or creators uploading to platforms that quietly compress (and often visibly degrade) anything too large themselves. The quality slider is the whole game here: dragging it down to 60-70% typically cuts file size dramatically with compression artifacts most people won't notice, while staying above 85% keeps virtually all visual detail at a smaller — if less dramatic — savings. For a batch of photos going on the same page, compressing each one to a similar target size, rather than a uniform quality percentage, tends to give the most consistent-looking result.",
    category: "image-studio",
    iconName: "Minimize2",
    keywords: ["image compressor", "compress image", "reduce image size"],
    status: "live",
    addedAt: "2026-10-22",
    applicationCategory: "UtilitiesApplication",
    relatedToolsLimit: 6,
    faq: COMPRESSOR_FAQ_ITEMS,
    example: COMPRESSOR_EXAMPLE,
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    tagline: "Exact dimensions, in seconds.",
    description:
      "Resize an image to specific pixel dimensions — processed entirely in your browser, nothing uploaded.",
    introParagraph:
      "Every platform has its own preferred dimensions — a thumbnail here, a banner there, a specific aspect ratio for an ad unit — and resizing images one-off in a heavyweight photo editor is disproportionate effort for what's usually a thirty-second task. The Image Resizer runs entirely in your browser: upload an image, set the exact width and height you need, and download the result, with no file ever leaving your device or touching a server. It's aimed at anyone who needs a quick, precise resize without opening design software — a marketer prepping assets for five different ad platforms, a seller resizing product photos to a marketplace's exact spec, a student formatting an image for a document with a strict size limit. Because width and height are set independently rather than automatically locked to the original ratio, it's worth entering dimensions that match your source image's proportions if you want to avoid visible stretching; for anything where the ratio itself needs to change intentionally, that flexibility is exactly the point.",
    category: "image-studio",
    iconName: "Maximize2",
    keywords: ["image resizer", "resize image", "change image dimensions"],
    status: "live",
    addedAt: "2026-10-23",
    applicationCategory: "UtilitiesApplication",
    relatedToolsLimit: 6,
    faq: RESIZER_FAQ_ITEMS,
    example: RESIZER_EXAMPLE,
  },
  {
    slug: "png-to-jpg-converter",
    name: "PNG to JPG Converter",
    tagline: "Smaller files for photos, not graphics.",
    description:
      "Convert a PNG image to JPG format — processed entirely in your browser, nothing uploaded.",
    category: "image-studio",
    iconName: "FileImage",
    keywords: ["png to jpg", "png to jpg converter", "convert png to jpeg"],
    status: "live",
    addedAt: "2026-10-24",
    applicationCategory: "UtilitiesApplication",
    relatedToolsLimit: 6,
    faq: PNG_TO_JPG_FAQ_ITEMS,
    example: PNG_TO_JPG_EXAMPLE,
  },
  {
    slug: "jpg-to-png-converter",
    name: "JPG to PNG Converter",
    tagline: "Lossless, ready for further editing.",
    description:
      "Convert a JPG image to PNG format — processed entirely in your browser, nothing uploaded.",
    category: "image-studio",
    iconName: "Image",
    keywords: ["jpg to png", "jpg to png converter", "convert jpeg to png"],
    status: "live",
    addedAt: "2026-10-25",
    applicationCategory: "UtilitiesApplication",
    relatedToolsLimit: 6,
    faq: JPG_TO_PNG_FAQ_ITEMS,
    example: JPG_TO_PNG_EXAMPLE,
  },
  {
    slug: "webp-converter",
    name: "WebP Converter",
    tagline: "Smaller images, faster pages.",
    description:
      "Convert a JPG or PNG image to WebP format for smaller file sizes — processed entirely in your browser, nothing uploaded.",
    category: "image-studio",
    iconName: "RefreshCw",
    keywords: ["webp converter", "convert to webp", "jpg to webp", "png to webp"],
    status: "live",
    addedAt: "2026-10-26",
    applicationCategory: "UtilitiesApplication",
    relatedToolsLimit: 6,
    faq: WEBP_FAQ_ITEMS,
    example: WEBP_EXAMPLE,
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    tagline: "See exactly what's inside a token.",
    description:
      "Decode a JWT's header and payload to inspect its claims, including expiration. Signature is not verified — that requires a key this tool never has.",
    introParagraph:
      "A JWT looks like an opaque string of characters, but it's actually just base64url-encoded JSON in disguise — readable by anyone the moment they know how to decode it, which is exactly what makes debugging authentication issues so much faster once you can see what's actually inside a given token. The JWT Decoder splits a token into its header and payload, decodes both back to readable JSON, and flags whether the token has already expired based on its `exp` claim — all without ever touching the signature, which requires a secret key this browser-based tool never has and has no business asking for. It's a routine debugging tool for developers working with authentication — checking what claims a token actually carries, confirming an expiration time matches what's expected, or verifying a backend is issuing tokens with the right shape. It's worth remembering this only decodes, never verifies: a token's contents are visible to anyone holding it whether or not its signature is actually valid, so never rely on a JWT's payload alone as proof of anything without server-side signature verification too.",
    category: "developer",
    iconName: "Lock",
    keywords: ["jwt decoder", "decode jwt", "json web token", "jwt debugger"],
    status: "live",
    addedAt: "2026-10-27",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: JWT_FAQ_ITEMS,
    example: JWT_EXAMPLE,
  },
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder / Decoder",
    tagline: "Safe for query strings, either direction.",
    description:
      "Encode or decode a URL component — turn unsafe characters into percent-encoded escapes, or read a percent-encoded string back into plain text.",
    category: "developer",
    iconName: "Link",
    keywords: ["url encoder", "url decoder", "percent encoding", "encodeuricomponent"],
    status: "live",
    addedAt: "2026-10-28",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: URL_CODEC_FAQ_ITEMS,
    example: URL_CODEC_EXAMPLE,
  },
  {
    slug: "seo-slug-generator",
    name: "Slug Generator",
    tagline: "Clean URLs, every time.",
    description:
      "Convert any text into a clean, URL-safe slug — lowercase, hyphenated, with diacritics correctly stripped to their plain-letter equivalents.",
    category: "marketing",
    iconName: "Type",
    keywords: ["slug generator", "url slug", "seo slug", "url friendly text"],
    status: "live",
    addedAt: "2026-10-29",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 9,
    faq: SLUG_FAQ_ITEMS,
    example: SLUG_EXAMPLE,
  },
  {
    slug: "json-to-csv-converter",
    name: "JSON to CSV Converter",
    tagline: "Your JSON array, ready for a spreadsheet.",
    description:
      "Convert a JSON array of objects into CSV — correctly handles mismatched fields across objects and quotes values that contain commas.",
    category: "data",
    iconName: "Table",
    keywords: ["json to csv", "json to csv converter", "convert json to spreadsheet"],
    status: "live",
    addedAt: "2026-10-30",
    applicationCategory: "DeveloperApplication",
    relatedToolsLimit: 9,
    faq: JSON_TO_CSV_FAQ_ITEMS,
    example: JSON_TO_CSV_EXAMPLE,
  },
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    tagline: "Add it, remove it, see the split.",
    description:
      "Calculate India's GST either way — add tax to a pre-tax amount, or extract it from a tax-inclusive amount — with a CGST/SGST breakdown.",
    introParagraph:
      "GST math is simple in principle — a fixed percentage added to or extracted from an amount — but doing it correctly by hand, especially the extraction direction (working backward from a tax-inclusive price to find the original amount), is easy to get subtly wrong, and being off by even a little matters on an invoice. The GST Calculator handles both directions explicitly: add GST to a pre-tax amount to get the final price, or enter a tax-inclusive amount and extract exactly how much of it was tax, with a CGST/SGST split shown for intra-state transactions. It's aimed at small business owners writing invoices, freelancers pricing their services, and anyone in India who needs a quick, reliable GST figure without opening a spreadsheet. The standard slabs (5%, 12%, 18%, 28%) are one tap away, but double-check the applicable rate for your specific goods or service before relying on the output for actual filing — this tool gets the math exactly right, but which rate applies is a separate question worth confirming against an official source.",
    category: "finance",
    iconName: "Receipt",
    keywords: ["gst calculator", "gst calculation india", "cgst sgst calculator"],
    status: "live",
    addedAt: "2026-10-31",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: GST_FAQ_ITEMS,
    example: GST_EXAMPLE,
  },
];

/** All tools, live or upcoming. */
export function getAllTools(): ToolDefinition[] {
  return TOOLS;
}

/** Only tools that are actually usable right now. */
export function getLiveTools(): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.status === "live");
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(categorySlug: string): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === categorySlug);
}

/** Tools sorted newest-first by `addedAt`, for the homepage's "Recently added" rail. */
export function getRecentlyAddedTools(limit = 6): ToolDefinition[] {
  return [...TOOLS]
    .sort((a, b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime())
    .slice(0, limit);
}

/**
 * Tools related to the given one: same group first, excluding itself,
 * capped at `limit`. "Group" is `relatedGroup` if the tool sets one
 * (letting two toolsets share a category but stay recommendation-scoped
 * to their own siblings), otherwise it falls back to `category`. Falls
 * back further to other live tools if the group is thin.
 */
export function getRelatedTools(tool: ToolDefinition, limit = 3): ToolDefinition[] {
  const group = tool.relatedGroup ?? tool.category;
  const sameGroup = TOOLS.filter(
    (candidate) => (candidate.relatedGroup ?? candidate.category) === group && candidate.slug !== tool.slug
  );

  if (sameGroup.length >= limit) {
    return sameGroup.slice(0, limit);
  }

  const fillers = TOOLS.filter(
    (candidate) => candidate.slug !== tool.slug && !sameGroup.includes(candidate)
  );

  return [...sameGroup, ...fillers].slice(0, limit);
}

/** Simple case-insensitive search across name, tagline, description, and keywords. */
export function searchTools(query: string): ToolDefinition[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return TOOLS;

  return TOOLS.filter((tool) => {
    const haystack = [tool.name, tool.tagline, tool.description, ...tool.keywords]
      .join(" ")
      .toLowerCase();
    return haystack.includes(normalized);
  });
}
