import type { ToolDefinition } from "./types";
import { EMI_FAQ_ITEMS, EMI_FORMULA, EMI_EXAMPLE } from "./tools/emi-calculator/constants";
import { SIP_FAQ_ITEMS, SIP_FORMULA, SIP_EXAMPLE } from "./tools/sip-calculator/constants";
import { LOAN_FAQ_ITEMS, LOAN_FORMULA, LOAN_EXAMPLE } from "./tools/loan-calculator/constants";
import { FD_FAQ_ITEMS, FD_FORMULA, FD_EXAMPLE } from "./tools/fd-calculator/constants";
import { RD_FAQ_ITEMS, RD_FORMULA, RD_EXAMPLE } from "./tools/rd-calculator/constants";
import { SWP_FAQ_ITEMS, SWP_FORMULA, SWP_EXAMPLE } from "./tools/swp-calculator/constants";
import {
  COMPOUND_INTEREST_FAQ_ITEMS,
  COMPOUND_INTEREST_FORMULA,
  COMPOUND_INTEREST_EXAMPLE,
} from "./tools/compound-interest-calculator/constants";
import {
  RETIREMENT_FAQ_ITEMS,
  RETIREMENT_FORMULA,
  RETIREMENT_EXAMPLE,
} from "./tools/retirement-calculator/constants";
import { CAGR_FAQ_ITEMS, CAGR_FORMULA, CAGR_EXAMPLE } from "./tools/cagr-calculator/constants";
import { YOUTUBE_GENERATOR_CONTENT } from "./tools/youtube-generator/tool-content";
import { TIMESTAMP_FAQ_ITEMS, TIMESTAMP_EXAMPLE } from "./tools/youtube-timestamp-generator/constants";
import { THUMBNAIL_FAQ_ITEMS, THUMBNAIL_EXAMPLE } from "./tools/youtube-thumbnail-downloader/constants";
import { INSTAGRAM_GENERATOR_CONTENT } from "./tools/instagram-generator/tool-content";
import {
  ENGAGEMENT_FAQ_ITEMS,
  ENGAGEMENT_EXAMPLE,
} from "./tools/instagram-engagement-calculator/constants";
import {
  CHARACTER_COUNTER_FAQ_ITEMS,
  CHARACTER_COUNTER_EXAMPLE,
} from "./tools/instagram-character-counter/constants";
import { LINKEDIN_GENERATOR_CONTENT } from "./tools/linkedin-generator/tool-content";
import { OPTIMIZER_FAQ_ITEMS, OPTIMIZER_EXAMPLE } from "./tools/linkedin-profile-optimizer/constants";
import {
  HEADLINE_ANALYZER_FAQ_ITEMS,
  HEADLINE_ANALYZER_EXAMPLE,
} from "./tools/linkedin-headline-analyzer/constants";
import {
  PROFILE_SEO_FAQ_ITEMS,
  PROFILE_SEO_EXAMPLE,
} from "./tools/linkedin-profile-seo-checker/constants";
import { TWITTER_GENERATOR_CONTENT } from "./tools/twitter-generator/tool-content";
import { FACEBOOK_GENERATOR_CONTENT } from "./tools/facebook-generator/tool-content";

/**
 * The tool catalog. To add tool #101, add one object here and drop its
 * component under `components/tools/<slug>/` (registering its loader in
 * `lib/tool-components.ts`). Nothing else — routing, the homepage grid,
 * category pages, search, breadcrumbs, and related tools — needs to
 * change.
 *
 * Every field here is plain, serializable data (strings, numbers,
 * booleans, arrays, and plain objects) — no component references, no
 * functions — so this array is safe to read from Client Components
 * (search, the tools browser) as well as Server Components.
 */
export const TOOLS: ToolDefinition[] = [
  {
    slug: "email-writer",
    name: "AI Email Writer",
    tagline: "Write the email. We'll find the words.",
    description:
      "Describe what you need to say, choose a tone and a length, and get a ready-to-send subject line and body in seconds.",
    category: "writing",
    iconName: "Mail",
    keywords: ["email", "writer", "generator", "ai", "professional email", "cover letter"],
    status: "live",
    addedAt: "2026-06-01",
  },
  {
    slug: "resume-builder",
    name: "AI Resume Builder",
    tagline: "A sharper resume in one pass.",
    description:
      "Turn a rough work history into a clean, recruiter-ready resume, tailored to the role you're applying for.",
    category: "writing",
    iconName: "FileText",
    keywords: ["resume", "cv", "job application", "career"],
    status: "coming-soon",
    addedAt: "2026-06-01",
  },
  {
    slug: "meeting-notes-summarizer",
    name: "Meeting Notes Summarizer",
    tagline: "Raw notes in, clear action items out.",
    description:
      "Paste messy meeting notes or a transcript and get a structured summary with decisions and action items.",
    category: "productivity",
    iconName: "ListChecks",
    keywords: ["meetings", "notes", "summary", "action items", "productivity"],
    status: "coming-soon",
    addedAt: "2026-06-01",
  },
  {
    slug: "regex-generator",
    name: "Regex Generator",
    tagline: "Describe the pattern, get the regex.",
    description:
      "Explain what you're trying to match in plain English and get a tested, explained regular expression.",
    category: "developer",
    iconName: "Braces",
    keywords: ["regex", "regular expression", "developer", "pattern matching"],
    status: "coming-soon",
    addedAt: "2026-06-01",
  },
  {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    tagline: "A palette that actually goes together.",
    description:
      "Generate accessible, harmonious color palettes from a mood, a brand word, or a base color.",
    category: "design",
    iconName: "Palette",
    keywords: ["colors", "palette", "design", "branding", "ui"],
    status: "coming-soon",
    addedAt: "2026-06-01",
  },
  {
    slug: "seo-meta-generator",
    name: "SEO Meta Tag Generator",
    tagline: "Titles and descriptions that earn the click.",
    description:
      "Generate optimized title tags, meta descriptions, and Open Graph copy for any page.",
    category: "marketing",
    iconName: "Tags",
    keywords: ["seo", "meta tags", "marketing", "open graph"],
    status: "coming-soon",
    addedAt: "2026-06-01",
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON Converter",
    tagline: "Clean tabular data, structured instantly.",
    description:
      "Paste or upload a CSV and get well-formed, typed JSON out — no spreadsheet software required.",
    category: "data",
    iconName: "FileJson",
    keywords: ["csv", "json", "convert", "data", "file conversion"],
    status: "coming-soon",
    addedAt: "2026-06-01",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    tagline: "Know your monthly payment before you sign.",
    description:
      "Calculate your monthly loan installment (EMI), total interest, and full amortization schedule from your loan amount, interest rate, and tenure.",
    category: "finance",
    iconName: "Calculator",
    keywords: [
      "emi",
      "emi calculator",
      "loan calculator",
      "amortization",
      "monthly installment",
      "interest calculator",
      "mortgage calculator",
    ],
    status: "live",
    addedAt: "2026-07-23",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: EMI_FAQ_ITEMS,
    formula: EMI_FORMULA,
    example: EMI_EXAMPLE,
  },
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    tagline: "See what consistent investing actually adds up to.",
    description:
      "Project your SIP's final corpus, total returns, and CAGR from a monthly investment, expected return rate, and investment period — with optional annual step-up and inflation adjustment.",
    category: "finance",
    iconName: "TrendingUp",
    keywords: [
      "sip",
      "sip calculator",
      "systematic investment plan",
      "mutual fund calculator",
      "investment calculator",
      "compound interest",
      "wealth calculator",
      "step-up sip",
    ],
    status: "live",
    addedAt: "2026-07-24",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: SIP_FAQ_ITEMS,
    formula: SIP_FORMULA,
    example: SIP_EXAMPLE,
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    tagline: "Find your EMI, or find what you can borrow.",
    description:
      "Calculate your monthly payment for a given loan amount, or flip it around and find the loan amount a target monthly payment can support.",
    category: "finance",
    iconName: "Banknote",
    keywords: ["loan calculator", "borrowing calculator", "affordability calculator", "loan amount", "monthly payment"],
    status: "live",
    addedAt: "2026-07-25",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: LOAN_FAQ_ITEMS,
    formula: LOAN_FORMULA,
    example: LOAN_EXAMPLE,
  },
  {
    slug: "fd-calculator",
    name: "FD Calculator",
    tagline: "See exactly what your fixed deposit will be worth.",
    description:
      "Calculate the maturity value and total interest on a fixed deposit from your deposit amount, interest rate, tenure, and compounding frequency.",
    category: "finance",
    iconName: "Lock",
    keywords: ["fd calculator", "fixed deposit calculator", "maturity value", "deposit calculator", "bank deposit"],
    status: "live",
    addedAt: "2026-07-26",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: FD_FAQ_ITEMS,
    formula: FD_FORMULA,
    example: FD_EXAMPLE,
  },
  {
    slug: "rd-calculator",
    name: "RD Calculator",
    tagline: "Small monthly deposits, projected to maturity.",
    description:
      "Calculate your recurring deposit's maturity value and total interest from a monthly deposit amount, interest rate, and tenure.",
    category: "finance",
    iconName: "RefreshCw",
    keywords: ["rd calculator", "recurring deposit calculator", "maturity value", "monthly deposit"],
    status: "live",
    addedAt: "2026-07-27",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: RD_FAQ_ITEMS,
    formula: RD_FORMULA,
    example: RD_EXAMPLE,
  },
  {
    slug: "swp-calculator",
    name: "SWP Calculator",
    tagline: "Turn a lump sum into a monthly income.",
    description:
      "Project how long a lump-sum investment lasts under a systematic withdrawal plan — see your final balance, total withdrawn, and interest earned.",
    category: "finance",
    iconName: "TrendingDown",
    keywords: ["swp calculator", "systematic withdrawal plan", "withdrawal calculator", "retirement income"],
    status: "live",
    addedAt: "2026-07-28",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: SWP_FAQ_ITEMS,
    formula: SWP_FORMULA,
    example: SWP_EXAMPLE,
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    tagline: "See how your money grows on itself.",
    description:
      "Calculate compound growth on a lump sum from a principal, annual rate, time period, and compounding frequency.",
    category: "finance",
    iconName: "Percent",
    keywords: ["compound interest calculator", "interest calculator", "growth calculator", "compounding"],
    status: "live",
    addedAt: "2026-07-29",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: COMPOUND_INTEREST_FAQ_ITEMS,
    formula: COMPOUND_INTEREST_FORMULA,
    example: COMPOUND_INTEREST_EXAMPLE,
  },
  {
    slug: "retirement-calculator",
    name: "Retirement Calculator",
    tagline: "See what your savings could grow into by retirement.",
    description:
      "Project your retirement corpus from your current age, retirement age, current savings, monthly contribution, and expected return.",
    category: "finance",
    iconName: "PiggyBank",
    keywords: ["retirement calculator", "retirement corpus", "retirement planning", "nest egg calculator"],
    status: "live",
    addedAt: "2026-07-30",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: RETIREMENT_FAQ_ITEMS,
    formula: RETIREMENT_FORMULA,
    example: RETIREMENT_EXAMPLE,
  },
  {
    slug: "cagr-calculator",
    name: "CAGR Calculator",
    tagline: "The one smoothed growth rate behind any two numbers.",
    description:
      "Calculate the Compound Annual Growth Rate between an initial and final value over a given time period.",
    category: "finance",
    iconName: "ArrowUpRight",
    keywords: ["cagr calculator", "compound annual growth rate", "growth rate calculator", "investment returns"],
    status: "live",
    addedAt: "2026-07-31",
    applicationCategory: "FinanceApplication",
    isCalculator: true,
    faq: CAGR_FAQ_ITEMS,
    formula: CAGR_FORMULA,
    example: CAGR_EXAMPLE,
  },
  {
    slug: "youtube-tag-generator",
    name: "YouTube Tag Generator",
    tagline: "Tags that actually help people find your video.",
    description:
      "Generate three ready-to-use sets of YouTube tags from your video's topic, mixing broad and long-tail keywords for better discoverability.",
    category: "creator-studio",
    iconName: "Tags",
    keywords: ["youtube tag generator", "youtube tags", "video seo", "youtube keywords"],
    status: "live",
    addedAt: "2026-08-01",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["tag-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["tag-generator"].example,
  },
  {
    slug: "youtube-title-generator",
    name: "YouTube Title Generator",
    tagline: "Titles that earn the click without the clickbait.",
    description:
      "Generate three compelling YouTube video title options from your topic — attention-grabbing, search-friendly, and true to your content.",
    category: "creator-studio",
    iconName: "Type",
    keywords: ["youtube title generator", "video title ideas", "youtube seo", "clickable titles"],
    status: "live",
    addedAt: "2026-08-02",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["title-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["title-generator"].example,
  },
  {
    slug: "youtube-description-generator",
    name: "YouTube Description Generator",
    tagline: "A full description draft, not just a blank box.",
    description:
      "Generate three complete, SEO-friendly YouTube video descriptions from your topic and key points — hook, context, and call to action included.",
    category: "creator-studio",
    iconName: "AlignLeft",
    keywords: ["youtube description generator", "video description", "youtube seo description"],
    status: "live",
    addedAt: "2026-08-03",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["description-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["description-generator"].example,
  },
  {
    slug: "youtube-hashtag-generator",
    name: "YouTube Hashtag Generator",
    tagline: "The right mix of broad and niche hashtags.",
    description:
      "Generate three sets of relevant YouTube hashtags for your video's topic, ready to paste into your description.",
    category: "creator-studio",
    iconName: "Hash",
    keywords: ["youtube hashtag generator", "youtube hashtags", "video hashtags"],
    status: "live",
    addedAt: "2026-08-04",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["hashtag-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["hashtag-generator"].example,
  },
  {
    slug: "youtube-channel-name-generator",
    name: "YouTube Channel Name Generator",
    tagline: "A name worth building a brand around.",
    description:
      "Generate three catchy, memorable YouTube channel name ideas from your niche or theme.",
    category: "creator-studio",
    iconName: "AtSign",
    keywords: ["youtube channel name generator", "channel name ideas", "youtube branding"],
    status: "live",
    addedAt: "2026-08-05",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["channel-name-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["channel-name-generator"].example,
  },
  {
    slug: "youtube-video-idea-generator",
    name: "YouTube Video Idea Generator",
    tagline: "Never stare at a blank content calendar again.",
    description:
      "Generate three specific, ready-to-film YouTube video ideas from your channel's niche or topic area.",
    category: "creator-studio",
    iconName: "Lightbulb",
    keywords: ["youtube video ideas", "content ideas generator", "youtube video topics"],
    status: "live",
    addedAt: "2026-08-06",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["video-idea-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["video-idea-generator"].example,
  },
  {
    slug: "youtube-script-generator",
    name: "YouTube Script Generator",
    tagline: "A hook, a body, and an outro — drafted for you.",
    description:
      "Generate three complete YouTube video script drafts from your topic, each with a hook, organized main content, and outro.",
    category: "creator-studio",
    iconName: "ScrollText",
    keywords: ["youtube script generator", "video script writer", "youtube script template"],
    status: "live",
    addedAt: "2026-08-07",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["script-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["script-generator"].example,
  },
  {
    slug: "youtube-keyword-generator",
    name: "YouTube Keyword Generator",
    tagline: "Search phrases real viewers actually type.",
    description:
      "Generate three sets of SEO keyword phrases for your video or channel topic, for use in titles, descriptions, and scripts.",
    category: "creator-studio",
    iconName: "KeyRound",
    keywords: ["youtube keyword generator", "youtube keyword research", "video seo keywords"],
    status: "live",
    addedAt: "2026-08-08",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: YOUTUBE_GENERATOR_CONTENT["keyword-generator"].faq,
    example: YOUTUBE_GENERATOR_CONTENT["keyword-generator"].example,
  },
  {
    slug: "youtube-timestamp-generator",
    name: "YouTube Timestamp Generator",
    tagline: "Chapter markers, calculated instantly.",
    description:
      "Turn a list of chapter titles and their lengths into ready-to-paste YouTube timestamps, calculated automatically.",
    category: "creator-studio",
    iconName: "Timer",
    keywords: ["youtube timestamp generator", "video chapters", "youtube chapter markers"],
    status: "live",
    addedAt: "2026-08-09",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: TIMESTAMP_FAQ_ITEMS,
    example: TIMESTAMP_EXAMPLE,
  },
  {
    slug: "youtube-thumbnail-downloader",
    name: "YouTube Thumbnail Downloader",
    tagline: "Every resolution, one paste away.",
    description:
      "Paste any YouTube video URL to preview and download its thumbnail in every available resolution.",
    category: "creator-studio",
    iconName: "Youtube",
    keywords: ["youtube thumbnail downloader", "download youtube thumbnail", "youtube thumbnail grabber"],
    status: "live",
    addedAt: "2026-08-10",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "youtube",
    faq: THUMBNAIL_FAQ_ITEMS,
    example: THUMBNAIL_EXAMPLE,
  },
  {
    slug: "instagram-caption-generator",
    name: "Instagram Caption Generator",
    tagline: "Captions that sound like you, not an ad.",
    description:
      "Generate three engaging Instagram caption options from your post's topic — authentic, conversational, and ready to post.",
    category: "creator-studio",
    iconName: "MessageCircle",
    keywords: ["instagram caption generator", "instagram captions", "caption ideas"],
    status: "live",
    addedAt: "2026-08-11",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["caption-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["caption-generator"].example,
  },
  {
    slug: "instagram-hashtag-generator",
    name: "Instagram Hashtag Generator",
    tagline: "The right mix, from broad reach to niche discovery.",
    description:
      "Generate three sets of relevant Instagram hashtags for your post, mixing broad and niche-specific tags for better reach.",
    category: "creator-studio",
    iconName: "Hash",
    keywords: ["instagram hashtag generator", "instagram hashtags", "hashtags for instagram"],
    status: "live",
    addedAt: "2026-08-12",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["hashtag-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["hashtag-generator"].example,
  },
  {
    slug: "instagram-bio-generator",
    name: "Instagram Bio Generator",
    tagline: "150 characters, made to count.",
    description:
      "Generate three Instagram bio options from a short description of your account — clear, on-brand, and within the 150-character limit.",
    category: "creator-studio",
    iconName: "UserCircle",
    keywords: ["instagram bio generator", "instagram bio ideas", "bio for instagram"],
    status: "live",
    addedAt: "2026-08-13",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["bio-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["bio-generator"].example,
  },
  {
    slug: "instagram-username-generator",
    name: "Instagram Username Generator",
    tagline: "A handle worth building a brand around.",
    description:
      "Generate three catchy, memorable Instagram username ideas from your name or niche.",
    category: "creator-studio",
    iconName: "AtSign",
    keywords: ["instagram username generator", "instagram handle ideas", "username ideas"],
    status: "live",
    addedAt: "2026-08-14",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["username-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["username-generator"].example,
  },
  {
    slug: "instagram-reel-caption-generator",
    name: "Instagram Reel Caption Generator",
    tagline: "A hook fast enough for a fast format.",
    description:
      "Generate three short, punchy Instagram Reel captions from your video's topic, built for the quick pace of short-form video.",
    category: "creator-studio",
    iconName: "Film",
    keywords: ["instagram reel caption generator", "reel captions", "reels caption ideas"],
    status: "live",
    addedAt: "2026-08-15",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["reel-caption-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["reel-caption-generator"].example,
  },
  {
    slug: "instagram-post-idea-generator",
    name: "Instagram Post Idea Generator",
    tagline: "Never stare at a blank content calendar again.",
    description:
      "Generate three specific, ready-to-shoot Instagram post ideas from your account's niche.",
    category: "creator-studio",
    iconName: "Lightbulb",
    keywords: ["instagram post ideas", "content ideas generator", "instagram content calendar"],
    status: "live",
    addedAt: "2026-08-16",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["post-idea-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["post-idea-generator"].example,
  },
  {
    slug: "instagram-story-caption-generator",
    name: "Instagram Story Caption Generator",
    tagline: "Quick, casual, and gone in 24 hours.",
    description:
      "Generate three short, casual Instagram Story captions from what's happening in the moment.",
    category: "creator-studio",
    iconName: "Aperture",
    keywords: ["instagram story caption generator", "story captions", "instagram stories ideas"],
    status: "live",
    addedAt: "2026-08-17",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["story-caption-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["story-caption-generator"].example,
  },
  {
    slug: "instagram-quote-generator",
    name: "Instagram Quote Generator",
    tagline: "Original, shareable, ready for a quote graphic.",
    description:
      "Generate three original, shareable quotes on any theme, ready to use on an Instagram quote graphic or caption.",
    category: "creator-studio",
    iconName: "Quote",
    keywords: ["instagram quote generator", "quote graphics", "shareable quotes"],
    status: "live",
    addedAt: "2026-08-18",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: INSTAGRAM_GENERATOR_CONTENT["quote-generator"].faq,
    example: INSTAGRAM_GENERATOR_CONTENT["quote-generator"].example,
  },
  {
    slug: "instagram-engagement-calculator",
    name: "Instagram Engagement Calculator",
    tagline: "Know your rate before you compare it to anyone else's.",
    description:
      "Calculate your Instagram engagement rate from followers, likes, comments, shares, and saves — with a plain-language rating.",
    category: "creator-studio",
    iconName: "TrendingUp",
    keywords: ["instagram engagement calculator", "engagement rate calculator", "instagram engagement rate"],
    status: "live",
    addedAt: "2026-08-19",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: ENGAGEMENT_FAQ_ITEMS,
    example: ENGAGEMENT_EXAMPLE,
  },
  {
    slug: "instagram-character-counter",
    name: "Instagram Character Counter",
    tagline: "Know exactly how much room you have left.",
    description:
      "Count characters, words, hashtags, and mentions for an Instagram caption, bio, or comment — with a heads-up before you hit the limit.",
    category: "creator-studio",
    iconName: "Ruler",
    keywords: ["instagram character counter", "caption character count", "instagram bio character limit"],
    status: "live",
    addedAt: "2026-08-20",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "instagram",
    faq: CHARACTER_COUNTER_FAQ_ITEMS,
    example: CHARACTER_COUNTER_EXAMPLE,
  },
  {
    slug: "linkedin-headline-generator",
    name: "LinkedIn Headline Generator",
    tagline: "More than a job title, in 220 characters.",
    description:
      "Generate three compelling LinkedIn headline options from your role and focus — built to stand out in search and on your profile.",
    category: "linkedin-studio",
    iconName: "PenTool",
    keywords: ["linkedin headline generator", "linkedin headline ideas", "professional headline"],
    status: "live",
    addedAt: "2026-08-21",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["headline-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["headline-generator"].example,
  },
  {
    slug: "linkedin-about-generator",
    name: "LinkedIn About Generator",
    tagline: "Your career story, told in your own voice.",
    description:
      "Generate three LinkedIn About section drafts from your background and experience — a natural first-person narrative, not a résumé bullet list.",
    category: "linkedin-studio",
    iconName: "UserCircle",
    keywords: ["linkedin about generator", "linkedin about section", "linkedin bio generator"],
    status: "live",
    addedAt: "2026-08-22",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["about-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["about-generator"].example,
  },
  {
    slug: "linkedin-summary-generator",
    name: "LinkedIn Summary Generator",
    tagline: "The elevator-pitch version of your career.",
    description:
      "Generate three short, punchy professional summaries from your role and strengths — a compact bio for anywhere a full About section doesn't fit.",
    category: "linkedin-studio",
    iconName: "FileText",
    keywords: ["linkedin summary generator", "professional summary generator", "elevator pitch generator"],
    status: "live",
    addedAt: "2026-08-23",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["summary-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["summary-generator"].example,
  },
  {
    slug: "linkedin-post-generator",
    name: "LinkedIn Post Generator",
    tagline: "A hook worth stopping the scroll for.",
    description:
      "Generate three LinkedIn post drafts from your topic — a strong opening hook, genuine insight, and a takeaway that invites comments.",
    category: "linkedin-studio",
    iconName: "Newspaper",
    keywords: ["linkedin post generator", "linkedin post ideas", "linkedin content generator"],
    status: "live",
    addedAt: "2026-08-24",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["post-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["post-generator"].example,
  },
  {
    slug: "linkedin-experience-generator",
    name: "LinkedIn Experience Generator",
    tagline: "Bullet points that lead with impact.",
    description:
      "Generate three sets of LinkedIn work experience bullet points from your role and responsibilities — action-oriented and quantified where possible.",
    category: "linkedin-studio",
    iconName: "History",
    keywords: ["linkedin experience generator", "resume bullet points", "work experience description"],
    status: "live",
    addedAt: "2026-08-25",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["experience-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["experience-generator"].example,
  },
  {
    slug: "linkedin-skills-generator",
    name: "LinkedIn Skills Generator",
    tagline: "The skills recruiters are actually searching for.",
    description:
      "Generate three relevant LinkedIn skills lists from your role or industry, mixing technical and soft skills.",
    category: "linkedin-studio",
    iconName: "Award",
    keywords: ["linkedin skills generator", "linkedin skills list", "resume skills generator"],
    status: "live",
    addedAt: "2026-08-26",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["skills-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["skills-generator"].example,
  },
  {
    slug: "linkedin-recommendation-generator",
    name: "LinkedIn Recommendation Generator",
    tagline: "Specific praise, not generic compliments.",
    description:
      "Generate three LinkedIn recommendation drafts for a colleague from a description of your working relationship — genuine and specific, not generic praise.",
    category: "linkedin-studio",
    iconName: "ThumbsUp",
    keywords: ["linkedin recommendation generator", "linkedin recommendation examples", "colleague recommendation"],
    status: "live",
    addedAt: "2026-08-27",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["recommendation-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["recommendation-generator"].example,
  },
  {
    slug: "linkedin-connection-request-generator",
    name: "LinkedIn Connection Request Generator",
    tagline: "300 characters, made to count.",
    description:
      "Generate three personalized LinkedIn connection request messages from your context — genuine, specific, and within LinkedIn's 300-character limit.",
    category: "linkedin-studio",
    iconName: "UserPlus",
    keywords: ["linkedin connection request", "linkedin message generator", "networking message generator"],
    status: "live",
    addedAt: "2026-08-28",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["connection-request-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["connection-request-generator"].example,
  },
  {
    slug: "linkedin-company-description-generator",
    name: "LinkedIn Company Description Generator",
    tagline: "Say what your company does — clearly.",
    description:
      "Generate three LinkedIn Company Page description drafts from your business details — what you do, who you serve, and what makes you distinct.",
    category: "linkedin-studio",
    iconName: "Building2",
    keywords: ["linkedin company description", "company page about", "business description generator"],
    status: "live",
    addedAt: "2026-08-29",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["company-description-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["company-description-generator"].example,
  },
  {
    slug: "linkedin-job-description-generator",
    name: "LinkedIn Job Description Generator",
    tagline: "A posting candidates will actually read.",
    description:
      "Generate three LinkedIn job posting drafts from your role details — intro, responsibilities, and qualifications, structured the way LinkedIn postings are read.",
    category: "linkedin-studio",
    iconName: "ClipboardList",
    keywords: ["linkedin job description generator", "job posting generator", "job description template"],
    status: "live",
    addedAt: "2026-08-30",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: LINKEDIN_GENERATOR_CONTENT["job-description-generator"].faq,
    example: LINKEDIN_GENERATOR_CONTENT["job-description-generator"].example,
  },
  {
    slug: "linkedin-profile-optimizer",
    name: "LinkedIn Profile Optimizer",
    tagline: "Your existing text, made sharper.",
    description:
      "Paste your current LinkedIn headline or About section to get an improved rewrite plus specific, actionable reasons why it's stronger.",
    category: "linkedin-studio",
    iconName: "Wand2",
    keywords: ["linkedin profile optimizer", "linkedin profile improvement", "linkedin rewrite tool"],
    status: "live",
    addedAt: "2026-08-31",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: OPTIMIZER_FAQ_ITEMS,
    example: OPTIMIZER_EXAMPLE,
  },
  {
    slug: "linkedin-headline-analyzer",
    name: "LinkedIn Headline Analyzer",
    tagline: "Know what's working and what isn't.",
    description:
      "Score your LinkedIn headline against concrete, checkable criteria — length, value-signaling language, quantifiable detail, structure, and formatting.",
    category: "linkedin-studio",
    iconName: "Gauge",
    keywords: ["linkedin headline analyzer", "linkedin headline checker", "linkedin headline score"],
    status: "live",
    addedAt: "2026-09-01",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: HEADLINE_ANALYZER_FAQ_ITEMS,
    example: HEADLINE_ANALYZER_EXAMPLE,
  },
  {
    slug: "linkedin-profile-seo-checker",
    name: "LinkedIn Profile SEO Checker",
    tagline: "See your profile the way search does.",
    description:
      "Check your headline, About section, and skills against your target keywords — with a coverage breakdown and completeness findings.",
    category: "linkedin-studio",
    iconName: "Search",
    keywords: ["linkedin seo checker", "linkedin profile seo", "linkedin keyword checker"],
    status: "live",
    addedAt: "2026-09-02",
    applicationCategory: "BusinessApplication",
    relatedToolsLimit: 12,
    faq: PROFILE_SEO_FAQ_ITEMS,
    example: PROFILE_SEO_EXAMPLE,
  },
  {
    slug: "twitter-tweet-generator",
    name: "Twitter Tweet Generator",
    tagline: "Direct, sharp, and under 280 characters.",
    description:
      "Generate three tweet options from your topic — direct, clear, and written to fit X's character limit.",
    category: "creator-studio",
    iconName: "MessageSquare",
    keywords: ["tweet generator", "twitter post generator", "x post generator"],
    status: "live",
    addedAt: "2026-09-03",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["tweet-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["tweet-generator"].example,
  },
  {
    slug: "twitter-viral-tweet-generator",
    name: "Twitter Viral Tweet Generator",
    tagline: "Bolder hooks, sharper takes.",
    description:
      "Generate three tweet options built around bold hooks and sharp takes, structured for higher engagement potential.",
    category: "creator-studio",
    iconName: "Flame",
    keywords: ["viral tweet generator", "viral twitter post", "twitter engagement generator"],
    status: "live",
    addedAt: "2026-09-04",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["viral-tweet-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["viral-tweet-generator"].example,
  },
  {
    slug: "twitter-thread-generator",
    name: "Twitter Thread Generator",
    tagline: "A hook, then a payoff, tweet by tweet.",
    description:
      "Generate three complete X thread outlines from your topic — a strong hook followed by numbered, standalone tweets.",
    category: "creator-studio",
    iconName: "ListOrdered",
    keywords: ["twitter thread generator", "x thread generator", "thread outline generator"],
    status: "live",
    addedAt: "2026-09-05",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["thread-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["thread-generator"].example,
  },
  {
    slug: "twitter-bio-generator",
    name: "Twitter Bio Generator",
    tagline: "160 characters, full of personality.",
    description:
      "Generate three X bio options from your account description — punchy, specific, and within the 160-character limit.",
    category: "creator-studio",
    iconName: "UserCircle",
    keywords: ["twitter bio generator", "x bio generator", "twitter bio ideas"],
    status: "live",
    addedAt: "2026-09-06",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["bio-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["bio-generator"].example,
  },
  {
    slug: "twitter-username-generator",
    name: "Twitter Username Generator",
    tagline: "A handle worth building a following around.",
    description:
      "Generate three catchy, likely-available X handle ideas from your name or niche.",
    category: "creator-studio",
    iconName: "AtSign",
    keywords: ["twitter username generator", "x handle generator", "twitter handle ideas"],
    status: "live",
    addedAt: "2026-09-07",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["username-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["username-generator"].example,
  },
  {
    slug: "twitter-hashtag-generator",
    name: "Twitter Hashtag Generator",
    tagline: "Fewer, better hashtags.",
    description:
      "Generate three small, well-targeted X hashtag sets from your post's topic — quality over quantity.",
    category: "creator-studio",
    iconName: "Hash",
    keywords: ["twitter hashtag generator", "x hashtag generator", "twitter hashtags"],
    status: "live",
    addedAt: "2026-09-08",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["hashtag-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["hashtag-generator"].example,
  },
  {
    slug: "twitter-hook-generator",
    name: "Twitter Hook Generator",
    tagline: "The first line that earns the rest of the read.",
    description:
      "Generate three opening hook lines from your topic — for a standalone tweet or the first line of a thread.",
    category: "creator-studio",
    iconName: "Anchor",
    keywords: ["twitter hook generator", "tweet hook ideas", "thread opener generator"],
    status: "live",
    addedAt: "2026-09-09",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["hook-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["hook-generator"].example,
  },
  {
    slug: "twitter-poll-generator",
    name: "Twitter Poll Generator",
    tagline: "A clear question, options included.",
    description:
      "Generate three X poll options from your topic — a clear question with 2-4 short answer choices, ready to post.",
    category: "creator-studio",
    iconName: "BarChart3",
    keywords: ["twitter poll generator", "x poll generator", "twitter poll ideas"],
    status: "live",
    addedAt: "2026-09-10",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["poll-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["poll-generator"].example,
  },
  {
    slug: "twitter-reply-generator",
    name: "Twitter Reply Generator",
    tagline: "A reply that could stand on its own.",
    description:
      "Generate three X reply options from the context of what you're responding to — adding genuine value, not just agreement.",
    category: "creator-studio",
    iconName: "Reply",
    keywords: ["twitter reply generator", "x reply generator", "tweet reply ideas"],
    status: "live",
    addedAt: "2026-09-11",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["reply-generator"].faq,
    example: TWITTER_GENERATOR_CONTENT["reply-generator"].example,
  },
  {
    slug: "twitter-content-calendar",
    name: "Twitter Content Calendar",
    tagline: "A week of ideas, planned in one pass.",
    description:
      "Generate three 7-day X content calendar options from your account's niche — a specific, varied post idea for each day.",
    category: "creator-studio",
    iconName: "Calendar",
    keywords: ["twitter content calendar", "x content calendar", "twitter posting schedule"],
    status: "live",
    addedAt: "2026-09-12",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "twitter",
    faq: TWITTER_GENERATOR_CONTENT["content-calendar"].faq,
    example: TWITTER_GENERATOR_CONTENT["content-calendar"].example,
  },
  {
    slug: "facebook-caption-generator",
    name: "Facebook Caption Generator",
    tagline: "Warm, conversational, ready to post.",
    description:
      "Generate three Facebook caption options from your photo or post topic — warm and conversational, Facebook's natural register.",
    category: "creator-studio",
    iconName: "MessageCircle",
    keywords: ["facebook caption generator", "facebook captions", "facebook photo caption"],
    status: "live",
    addedAt: "2026-09-13",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["caption-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["caption-generator"].example,
  },
  {
    slug: "facebook-post-generator",
    name: "Facebook Post Generator",
    tagline: "Room to tell the whole update.",
    description:
      "Generate three Facebook post drafts from your topic — a bit longer and more conversational than other platforms, the way Facebook posts read best.",
    category: "creator-studio",
    iconName: "Newspaper",
    keywords: ["facebook post generator", "facebook post ideas", "facebook content generator"],
    status: "live",
    addedAt: "2026-09-14",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["post-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["post-generator"].example,
  },
  {
    slug: "facebook-bio-generator",
    name: "Facebook Bio Generator",
    tagline: "255 characters that say exactly who you are.",
    description:
      "Generate three Facebook Page or profile bio options from your description — clear and within the 255-character limit.",
    category: "creator-studio",
    iconName: "UserCircle",
    keywords: ["facebook bio generator", "facebook page description", "facebook about section"],
    status: "live",
    addedAt: "2026-09-15",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["bio-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["bio-generator"].example,
  },
  {
    slug: "facebook-ad-copy-generator",
    name: "Facebook Ad Copy Generator",
    tagline: "The primary text that earns the click.",
    description:
      "Generate three Facebook ad primary text options from your offer — persuasive, benefit-led, and structured for the first two lines to earn attention.",
    category: "creator-studio",
    iconName: "Megaphone",
    keywords: ["facebook ad copy generator", "facebook ads copy", "facebook ad text generator"],
    status: "live",
    addedAt: "2026-09-16",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["ad-copy-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["ad-copy-generator"].example,
  },
  {
    slug: "facebook-headline-generator",
    name: "Facebook Headline Generator",
    tagline: "Bold text, 40 characters, straight to the point.",
    description:
      "Generate three Facebook ad headline options from your offer — the short, bold text shown above your ad's primary text.",
    category: "creator-studio",
    iconName: "Type",
    keywords: ["facebook headline generator", "facebook ad headline", "facebook ads headline ideas"],
    status: "live",
    addedAt: "2026-09-17",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["headline-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["headline-generator"].example,
  },
  {
    slug: "facebook-cta-generator",
    name: "Facebook CTA Generator",
    tagline: "A clear next step, not a vague nudge.",
    description:
      "Generate three call-to-action lines from the specific action you want readers to take — a clear, low-friction next step.",
    category: "creator-studio",
    iconName: "MousePointerClick",
    keywords: ["facebook cta generator", "call to action generator", "facebook ad cta"],
    status: "live",
    addedAt: "2026-09-18",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["cta-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["cta-generator"].example,
  },
  {
    slug: "facebook-comment-generator",
    name: "Facebook Comment Generator",
    tagline: "Sounds like a person, not a reply bot.",
    description:
      "Generate three Facebook comment options from the context of what you're responding to — natural, conversational, and genuinely additive.",
    category: "creator-studio",
    iconName: "MessageSquare",
    keywords: ["facebook comment generator", "facebook comment ideas", "facebook reply generator"],
    status: "live",
    addedAt: "2026-09-19",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["comment-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["comment-generator"].example,
  },
  {
    slug: "facebook-event-description-generator",
    name: "Facebook Event Description Generator",
    tagline: "Why someone should actually show up.",
    description:
      "Generate three Facebook Event description options from your event details — clear on what it is, who it's for, and why to attend.",
    category: "creator-studio",
    iconName: "CalendarDays",
    keywords: ["facebook event description", "facebook event generator", "event description ideas"],
    status: "live",
    addedAt: "2026-09-20",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["event-description-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["event-description-generator"].example,
  },
  {
    slug: "facebook-group-description-generator",
    name: "Facebook Group Description Generator",
    tagline: "Set the tone before anyone joins.",
    description:
      "Generate three Facebook Group description options from your group's purpose — clear about who it's for and what to expect.",
    category: "creator-studio",
    iconName: "Users",
    keywords: ["facebook group description", "facebook group generator", "group description ideas"],
    status: "live",
    addedAt: "2026-09-21",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["group-description-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["group-description-generator"].example,
  },
  {
    slug: "facebook-hashtag-generator",
    name: "Facebook Hashtag Generator",
    tagline: "A few well-chosen tags, not a wall of them.",
    description:
      "Generate three small, relevant Facebook hashtag sets from your post's topic.",
    category: "creator-studio",
    iconName: "Hash",
    keywords: ["facebook hashtag generator", "facebook hashtags", "facebook post hashtags"],
    status: "live",
    addedAt: "2026-09-22",
    applicationCategory: "MultimediaApplication",
    relatedToolsLimit: 9,
    relatedGroup: "facebook",
    faq: FACEBOOK_GENERATOR_CONTENT["hashtag-generator"].faq,
    example: FACEBOOK_GENERATOR_CONTENT["hashtag-generator"].example,
  },
];

/** All tools, live or upcoming. */
export function getAllTools(): ToolDefinition[] {
  return TOOLS;
}

/** Only tools that are actually usable right now. */
export function getLiveTools(): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.status === "live");
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(categorySlug: string): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === categorySlug);
}

/** Tools sorted newest-first by `addedAt`, for the homepage's "Recently added" rail. */
export function getRecentlyAddedTools(limit = 6): ToolDefinition[] {
  return [...TOOLS]
    .sort((a, b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime())
    .slice(0, limit);
}

/**
 * Tools related to the given one: same group first, excluding itself,
 * capped at `limit`. "Group" is `relatedGroup` if the tool sets one
 * (letting two toolsets share a category but stay recommendation-scoped
 * to their own siblings), otherwise it falls back to `category`. Falls
 * back further to other live tools if the group is thin.
 */
export function getRelatedTools(tool: ToolDefinition, limit = 3): ToolDefinition[] {
  const group = tool.relatedGroup ?? tool.category;
  const sameGroup = TOOLS.filter(
    (candidate) => (candidate.relatedGroup ?? candidate.category) === group && candidate.slug !== tool.slug
  );

  if (sameGroup.length >= limit) {
    return sameGroup.slice(0, limit);
  }

  const fillers = TOOLS.filter(
    (candidate) => candidate.slug !== tool.slug && !sameGroup.includes(candidate)
  );

  return [...sameGroup, ...fillers].slice(0, limit);
}

/** Simple case-insensitive search across name, tagline, description, and keywords. */
export function searchTools(query: string): ToolDefinition[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return TOOLS;

  return TOOLS.filter((tool) => {
    const haystack = [tool.name, tool.tagline, tool.description, ...tool.keywords]
      .join(" ")
      .toLowerCase();
    return haystack.includes(normalized);
  });
}
