import type { Metadata } from "next";
import { LegalPageShell } from "@/components/layout/legal-page-shell";
import { buildMetadata } from "@/lib/seo";
import { SITE_NAME, SITE_SUPPORT_EMAIL } from "@/lib/site-config";

export const metadata: Metadata = buildMetadata({
  title: "Disclaimer",
  description: `Important limitations to understand about AI-generated content and calculator results on ${SITE_NAME}.`,
  path: "/disclaimer",
});

const LAST_UPDATED = "January 2026";

export default function DisclaimerPage() {
  return (
    <LegalPageShell title="Disclaimer" lastUpdated={LAST_UPDATED}>
      <p>
        {SITE_NAME}'s AI Guide and AI-powered tools are built with real care to avoid one specific
        failure: recommending or generating something that doesn&apos;t reflect reality. But &quot;grounded&quot;
        doesn&apos;t mean &quot;infallible,&quot; and this page explains exactly what that means in practice.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Every AI-powered tool on this site — writing generators, the AI Guide, summarizers, and
        similar — uses Google&apos;s Gemini models to produce text. This text is a draft or suggestion,
        not a verified fact or a professional work product. Specifically:
      </p>
      <ul>
        <li>AI-generated writing (emails, resumes, social posts, and similar) may contain inaccuracies, awkward phrasing, or details that don't match your actual situation. Review and edit before using it for anything that matters.</li>
        <li>The AI Guide's tool recommendations are grounded in our real tool catalog — it only ever suggests tools that actually exist — but its judgment about which tool best fits your request is still a best-effort suggestion, not a guarantee of fit.</li>
        <li>A regex, code snippet, or technical output generated by an AI tool should be tested against your actual data before being relied on in anything production-facing.</li>
      </ul>

      <h2>Calculators and financial tools</h2>
      <p>
        The finance calculators on this site (EMI, SIP, loan, retirement, GST, and others) perform
        real, standard financial mathematics — they are not AI-generated and the formulas are
        deterministic. That said:
      </p>
      <ul>
        <li>Results are estimates based on the inputs you provide and standard formulas — actual outcomes from a lender, investment, or tax authority may differ due to fees, rounding conventions, changing rates, or rules specific to your situation.</li>
        <li>Nothing on this site constitutes financial, tax, investment, or legal advice. Always confirm figures that matter — a loan rate, a tax rate, an investment projection — with a qualified professional or an official source before acting on them.</li>
      </ul>

      <h2>Developer and utility tools</h2>
      <p>
        Tools like the JSON/CSS/JavaScript utilities, hash generator, and password generator use
        real, standard algorithms (documented in each tool&apos;s own FAQ) — not AI. They&apos;re built
        carefully and, where correctness is safety-critical (like cryptographic randomness for
        passwords), we use the browser&apos;s native, verified APIs rather than approximations. Still,
        always test output relevant to security or production systems in your own environment
        before depending on it.
      </p>

      <h2>No professional relationship</h2>
      <p>
        Using {SITE_NAME} does not create a professional, advisory, or fiduciary relationship
        between you and us. Tools here are aids, not substitutes for professional judgment in
        legal, medical, financial, or other regulated domains.
      </p>

      <h2>Your responsibility</h2>
      <p>
        You&apos;re responsible for reviewing, verifying, and taking ownership of anything you use from
        this site before relying on it — the same way you would with a draft from any other source.
      </p>

      <h2>Contact</h2>
      <p>
        If you find a tool producing output that&apos;s clearly wrong (not just imperfect, but actually
        incorrect), please <a href="/contact">report it</a> — this is exactly the kind of feedback
        that keeps the &quot;grounded, not fabricated&quot; standard real rather than aspirational. Or email
        us directly: <a href={`mailto:${SITE_SUPPORT_EMAIL}`}>{SITE_SUPPORT_EMAIL}</a>.
      </p>
    </LegalPageShell>
  );
}
